---
params: 
    title: ""
    Pars: "`r list()`"
    plotPars: "`r list()`"
    tabs: "`r TRUE`"
    its: " `r numeric()`"
    nyears: " `r numeric()`"
    proyears: " `r numeric()`"
    date: "`r Sys.Date()`"
title: "`r params$title`"
date: "`r params$date`"
output:
  html_document
---


```{r catchability, echo=FALSE, results="asis"}
if (params$tabs) {
  cat('### Future Catchability {.tabset .tabset-fade .tabset-pills}' )
} else {
  cat('### Future Catchability')
}

dd <- params$Pars$Stock$M_ageArray %>% dim()
nsim <- dd[1]
maxage <- dd[2]

nsamp <- length(params$its)
```

#### Sampled Parameters
Histograms of `r nsim` simulations of inter-annual variability in fishing efficiency (`qcv`) and average annual change in fishing efficiency (`qinc`), with vertical colored lines indicating `r nsamp` randomly drawn values used in the time-series plot:

```{r q_parameters, echo=FALSE}
MSEtool:::plot.Catchability(params$Pars, nsamp=nsamp, plotPars=params$plotPars, plot.num=1)
```


#### Time-Series
Time-series plot showing `r nsamp` trends in future fishing efficiency (catchability):

```{r q_time-series, echo=FALSE}
MSEtool:::plot.Catchability(params$Pars, nsamp=nsamp, plotPars=params$plotPars, plot.num=2)
```
