---
params: 
    title: ""
    Pars: "`r list()`"
    plotPars: "`r list()`"
    tabs: "`r TRUE`"
    its: " `r numeric()`"
    nyears: " `r numeric()`"
    proyears: " `r numeric()`"
    date: "`r Sys.Date()`"
title: "`r params$title`"
date: "`r params$date`"
output:
  html_document
---


```{r, echo=FALSE, results="asis"}
if (params$tabs) {
  cat('### Depletion and Discard Mortality {.tabset .tabset-fade .tabset-pills}' )
} else {
  cat('### Depletion and Discard Mortality')
}
dd <- dim(params$Pars$M_ageArray)
nsim <- dd[1]
maxage <- dd[2]

nsamp <- length(params$its)

```

#### Sampled Parameters 
Histograms of `r nsim` simulations of depletion (spawning biomass in the last historical year over average unfished spawning biomass; `D`) and the fraction of discarded fish that are killed by fishing mortality (`Fdisc`), with vertical colored lines indicating `r nsamp` randomly drawn values.

```{r, echo=FALSE}
MSEtool:::plot.Depletion(params$Pars, nsamp=nsamp, plotPars=params$plotPars)
```


