library(r4ss)
library(dplyr)
library(ggplot2)

devtools::load_all()

# go through all SS OMs ....
# and those in https://www.pcouncil.org/stock-assessments-star-reports-stat-reports-rebuilding-analyses-terms-of-reference/groundfish-stock-assessment-documents/
SSdirSWO <- "G:/My Drive/1_Projects/North_Atlantic_Swordfish/OMs/grid_2021/grid_May2021_shifted/40-M0.1_sigmaR0.6_steepness0.6_cpuelambda20_llq1_env-4_iter40"
replistSWO <- r4ss::SS_output(SSdirSWO)

replistSWO$SS_version


# SSdir <- 'G:/Shared drives/BM shared/4. Resources/3_OM_case_studies/Skipjack_IO_IOTC/data/io_h80_MeAs_t4_rtss_tm15'
# replist <- r4ss::SS_output(SSdir)

replist <- replistSWO


MOM <- SS2MOM(replist, nsim=3)
multiHist <- SimulateMOM(MOM)
sfStop()


OM <- SSMOM2OM(MOM, replist)
Hist <- Simulate(OM)
plot_SS2OM(Hist, SSdir)



nsim =3 
proyears = 50; reps = 1; maxF = 3; seed = 1;
interval = 1; pstar = 0.5;
Obs = MSEtool::Generic_Obs; Imp = MSEtool::Perfect_Imp; silent = FALSE;
Name = "MOM generated by SS2MOM"; Source = "No Source provided"

i <-1
single_sex = TRUE
age_M = NULL; mean_h = TRUE; seed = 1
partition = 2



## FIX THIS 
## test with SWO and all the rest in the G: folder

multiHist <- SimulateMOM(MOM)
sfStop()


replist$ageselex$Factor %>% unique()
[1] "Asel"         "Fecund"       "Asel2"        "F"            "bodywt"       "sel*wt"       "sel*ret*wt"   "sel_nums"    
[9] "sel*ret_nums" "dead_nums"    "dead*wt"

replist$ageselex %>% filter(Factor=='F', Yr==1993, Fleet==1)
Fs[,1]


# ----- Numbers -------

compareN <- function(replist, Hist) {
  year_lab <- "Year"
  mainyrs <- replist$startyr:replist$endyr
  
  if ('multiHist' %in% class(Hist)) {
    multiHist <- Hist
    n.yrs <- dim(multiHist[[1]][[1]]@TSdata$Number)[2]
    nsim <- dim(multiHist[[1]][[1]]@TSdata$Number)[1]
    if(n.yrs == length(mainyrs)) {
      OM_years <- replist$startyr:replist$endyr
    } else {
      nseas <- 1/replist$seasdurations
      year_frac <- data.frame(mainyrs = mainyrs, seas = rep(1:nseas, length(mainyrs)/nseas), 
                              true_year = rep(1:(length(mainyrs)/nseas), each = nseas))
      age_frac <- data.frame(age = 0:OM@maxage) %>% mutate(true_age = floor(age/nseas))
      OM_years <- dplyr::filter(year_frac, seas == 1) %>% getElement("mainyrs")
    }
    N_SS <- replist$natage  %>% filter(Yr %in% OM_years, `Beg/Mid`=="B")
    cols <- which(colnames(N_SS)=='0'):ncol(replist$natage)
    N_SS <- N_SS %>% 
      tidyr::pivot_longer(cols=all_of(cols)) %>%
      group_by(Yr, Sex) %>%
      summarize(N=sum(value), .groups = 'keep')
    
    np <- length(multiHist)
    N_OMlist <- list()
    for (p in 1:np) {
      N_OMlist[[p]] <- data.frame(Sim=1:nsim, 
                                  Yr=rep(mainyrs, each=nsim), 
                                  Sex=rep(p, nsim*n.yrs),
                                  N=c(as.vector(apply(multiHist[[p]][[1]]@TSdata$Number, 1:2, sum))))
    }
    N_OM <- do.call('rbind', N_OMlist)
    N_OM$Model <- 'OM'
    N_SS$Model <- 'SS'
    N_dat <- bind_rows(N_OM, N_SS)
    
    ggplot(N_dat, aes(x=Yr, y=N, color=Model, linetype=Model)) +
      facet_wrap(~Sex) +
      geom_line() +
      theme_bw() + 
      labs(x="Year", y="Total number")
  } else {
    
  }

}

compareN(replist, multiHist)

# ----- Spawning Biomass ----
mainyrs <- replist$startyr:replist$endyr
SB_SS <- replist$timeseries %>% dplyr::filter(Yr %in% mainyrs) %>% dplyr::select(Year=Yr, SB=SpawnBio)

n.yrs <- dim(multiHist[[1]][[1]]@TSdata$Number)[2]
nsim <- dim(multiHist[[1]][[1]]@TSdata$Number)[1]
SB_OM <- data.frame(Sim=1:nsim, 
                   Year=rep(mainyrs, each=nsim), 
                   SB=c(as.vector(apply(multiHist[[1]][[1]]@TSdata$SBiomass, 1:2, sum))))

SB_OM$Model <- 'OM'
SB_SS$Model <- 'SS'
SB_dat <- bind_rows(SB_OM, SB_SS)

ggplot(SB_dat, aes(x=Year, y=SB, color=Model, linetype=Model)) +
  geom_line() +
  theme_bw() + 
  labs(x="Year", y="Spawning Biomass")

# ----- Total Biomass ----
mainyrs <- replist$startyr:replist$endyr
B_SS <- replist$timeseries %>% dplyr::filter(Yr %in% mainyrs) %>% dplyr::select(Year=Yr, B=Bio_all)

n.p <- length(multiHist)
n.yrs <- dim(multiHist[[1]][[1]]@TSdata$Number)[2]
nsim <- dim(multiHist[[1]][[1]]@TSdata$Number)[1]

B_OMlist <- list()
for (p in 1:n.p) {
  B_OMlist[[p]] <- data.frame(Sim=1:nsim, 
                              Year=rep(mainyrs, each=nsim), 
                              Sex=p,
                              B=c(as.vector(apply(multiHist[[p]][[1]]@TSdata$Biomass, 1:2, sum))))
}
B_OM <- do.call('rbind', B_OMlist)
B_OM <- B_OM %>% group_by(Sim, Year) %>% summarise(B=sum(B), .groups = 'keep')

B_OM$Model <- 'OM'
B_SS$Model <- 'SS'
B_dat <- bind_rows(B_OM, B_SS)

ggplot(B_dat, aes(x=Year, y=B, color=Model, linetype=Model)) +
  geom_line() +
  theme_bw() + 
  labs(x="Year", y="Total Biomass")


# ----- Catch -----
# removals 
mainyrs <- replist$startyr:replist$endyr
C_SS <- replist$catch %>% dplyr::filter(Yr %in% mainyrs) %>%
  dplyr::select(Year=Yr, Fleet=Fleet, C=Exp)

n.p <- length(multiHist)
n.f <- length(multiHist[[1]])
n.yrs <- dim(multiHist[[1]][[1]]@TSdata$Number)[2]
nsim <- dim(multiHist[[1]][[1]]@TSdata$Number)[1]

C_OMlist <- list()
cnt <- 0
for (p in 1:n.p) {
  for (fl in 1:n.f) {
    cnt <- cnt+1
    C_OMlist[[cnt]] <- data.frame(Sim=1:nsim, 
                                Year=rep(mainyrs, each=nsim), 
                                Sex=p,
                                Fleet=fl,
                                C=c(as.vector(apply(multiHist[[p]][[fl]]@TSdata$Removals, 1:2, sum))),
                                R=c(as.vector(apply(multiHist[[p]][[fl]]@TSdata$Landings, 1:2, sum))))
    
  }
}
C_OM <- do.call('rbind', C_OMlist)
C_OM <- C_OM %>% group_by(Year, Fleet, Sim) %>% summarise(C=sum(C), R=sum(R), .groups = 'drop')

C_OM$Model <- 'OM'
C_SS$Model <- 'SS'
C_dat <- bind_rows(C_OM, C_SS)

ggplot(C_dat, aes(x=Year, y=C, color=Model, linetype=Model)) +
  geom_line() +
  facet_wrap(~Fleet, scales="free") +
  theme_bw() + 
  labs(x="Year", y="Catch by Fleet")


# Overall
C_dat_total <- C_dat %>% group_by(Year, Model, Sim) %>% summarise(Catch=sum(C), .groups = 'keep')

ggplot(C_dat_total, aes(x=Year, y=Catch, color=Model, linetype=Model)) +
  geom_line() +
  theme_bw() + 
  labs(x="Year", y="Catch")


C_OM %>% filter(Year==1993, Sim==1, Fleet==1)
C_SS %>% filter(Year==1993, Fleet==1)


# model SS approach and calculate catch and discards etc
OM_years <- replist$startyr:replist$endyr



N_SS <- replist$natage  %>% filter(Yr %in% OM_years, `Beg/Mid`=="B")
cols <- which(colnames(N_SS)=='0'):ncol(replist$natage)
N_SS <- N_SS %>% 
  tidyr::pivot_longer(cols=all_of(cols))  
N_SS$Age <- as.numeric(N_SS$name)


# N in 1993
N_SS <- N_SS %>% filter(Yr==1993) %>% select(Yr, Sex, Age, value)
N_SS$Number <- N_SS$value

which(OM_years==1993)
rowSums(multiHist[[1]][[1]]@AtAge$Number[1,,44,])
N_SS$Number 




wt <- replist$wtatage %>% filter(Yr==1993, Fleet==1)  %>% 
  tidyr::pivot_longer(cols=7:ncol(replist$wtatage))
wt$Age <- as.numeric(wt$name)
wt$weight <- wt$value
wt$value <- NULL


apicalF <- replist$exploitation %>% filter(Yr==1993) %>% 
  tidyr::pivot_longer(cols=7:ncol(replist$exploitation), names_to = 'Fleet', values_to='apicalF') %>% 
  select(Yr, annual_M, Fleet, apicalF)

n.fleet <- length(apicalF$Fleet %>% unique()) 

select <- replist$ageselex %>% filter(Factor=="Asel2", Yr==1993, Fleet==1) %>% 
  tidyr::pivot_longer(cols=8:ncol(replist$ageselex), names_to = 'Age', values_to='select') %>% 
  distinct(Yr, Sex, Fleet, Age, select)
select$Age <- as.numeric(select$Age)
maxage <- max(select$Age)

select <- list()
Fs <- list()
for (fl in 1:11) {
  select[[fl]] <- c(multiHist[[1]][[fl]]@SampPars$Fleet$V[1,,44], multiHist[[2]][[fl]]@SampPars$Fleet$V[1,,44])
  Fs[[fl]] <- select[[fl]] * apicalF$apicalF[fl]
}

select <- do.call(cbind, select)

Fs <- do.call(cbind, Fs)
Zs <- rowSums(Fs)+0.1

Zs[1:26]
Z[1,1,,44,1]


tt <- replist$ageselex %>% filter(Factor=='F', Yr==1993, Fleet==1)
myF <- c(as.vector(tt[1,8:ncol(tt)]), as.vector(tt[2,8:ncol(tt)]))  %>% unlist()

cc <- (N_SS$Number * wt$weight) * (1-exp(-Zs)) * (myF)/Zs
sum(cc)

cc <- (N_SS$Number * wt$weight) * (1-exp(-Zs)) * (Fs[,1])/Zs
sum(cc)


C_OM %>% filter(Year==1993, Sim==1, Fleet==1)
C_SS %>% filter(Year==1993, Fleet==1)


C_SS$C


6598/7023


6598/7023
6288/7023


multiHist[[1]][[1]]@TSdata$Find[1,43:45]
C_OM %>% filter(Sim==1, Fleet==1, Year==1993)
C_SS %>% filter(Fleet==1, Year==1993)


t1 <- C_OM %>% filter(Sim==1, Fleet==1)
t2 <- C_SS %>% filter(Fleet==1)

t2$C/t1$C

plot(t1$C)
lines(t2$C)








# Compare N-at-age
yrs <- replist$startyr:replist$endyr
n.yrs <- length(yrs)

sex <- 1
N_SS <- replist$natage %>% filter(Yr%in%yrs, `Beg/Mid`=='B', Sex==sex) %>% 
  tidyr::pivot_longer(cols=13:ncol(replist$natage)) %>% 
  select(Yr, Sex, Age=name, N=value)


N_age <- apply(multiHist[[sex]][[1]]@AtAge$Number[1,,,], 1:2, sum)
N_Sim <- data.frame(N_SS)
N_Sim$N <- as.vector(N_age)

N_SS$Model <- 'SS'
N_Sim$Model <- 'Sim'

yy <- 45
t1 <- N_SS %>% filter(Yr==yrs[yy]) %>% select(N)
t2 <- N_Sim %>% filter(Yr==yrs[yy])  %>% select(N)

t1$N
t2$N

y1 <- N_SS %>% filter(Yr==1950, Sex==1, Age==0)
y2 <- N_SS %>% filter(Yr==1951, Sex==1, Age==1)

# I simulate with 0 fishing mortality in year 1?
Vfleet <- array(NA, dim=c(26, 68, 11))

for (fl in 1:11) {
  Vfleet[,,fl] <- get_V_from_Asel2(fl, 1, replist, yrs, 25)
}

F1 <- 0 
for (fl in 1:11) {
  F1 <- F1 + multiHist[[1]][[fl]]@SampPars$Fleet$Find[1,1] * Vfleet[1,1,fl] # multiHist[[1]][[fl]]@SampPars$Fleet$V[1,1,1]
}


# what is the fishing mortality in year 1 ??
trueF <- F_at_age %>% filter(Age==0, Yr==1950, Sex==1) %>% summarise(F=sum(F))

trueF$F
F1



(y1$N * exp(-(0.1+F1)))
t1$N[2]
t2$N[2]

FF <- list()
for (fl in 1:11) {
  FF[[fl]] <- replist$exploitation[, match(replist$FleetNames[fl], colnames(replist$exploitation))] %>%
    aggregate(by = list(Yr = replist$exploitation$Yr), sum) %>% filter(Yr==1950) 
}

FF <- do.call('rbind', FF)
FF$x %>% sum()

Find <- FF$x[FF$Yr %in% mainyrs]





# calculated Fs
y1SS <- N_SS %>% filter(Yr==yrs[1]) %>% select(N)
y1Sim <- N_Sim %>% filter(Yr==yrs[1])  %>% select(N)

y2SS <- N_SS %>% filter(Yr==yrs[2]) %>% select(N)
y2Sim <- N_Sim %>% filter(Yr==yrs[2])  %>% select(N)

ind <- 2:nrow(y1SS)
ind2 <- ind-1

SimsF <- rep(0, 26)
for (fl in 1:11)
  SimsF <- SimsF + multiHist[[1]][[fl]]@SampPars$Fleet$Find[1,1] * multiHist[[1]][[1]]@SampPars$Fleet$V[1,,1] 


-log(y2SS$N[ind]/y1SS$N[ind2])
-log(y2Sim$N[ind]/y1Sim$N[ind2]) # this should match below?
SimsF + 0.1

# why aren't the three Fs identical ??

### UP TO HERE ### 

matchSS <- N_SS_f %>% filter(Sex==1, Yr==1950)

matchSS$predN1/y1SS$N
matchSS$predN1/y1Sim$N











N_Sim$diff <- N_Sim$N-N_SS$N
N_Sim$Age <- as.numeric(N_Sim$Age)

ggplot(N_Sim, aes(x=Yr, y=diff)) +
  facet_wrap(~Age) +
  geom_line()

# Recruitment 
rec <- replist$natage %>% filter(Yr%in%yrs, `Beg/Mid`=='B') %>% 
  tidyr::pivot_longer(cols=13:ncol(replist$natage)) %>% 
  select(Yr, Sex, Age=name, N=value) %>%
  mutate(Age=as.numeric(Age)) %>%
  filter(Age==0) %>%
  group_by(Yr) %>%
  summarize(Rec=sum(N))


SimRec <- apply(multiHist[[1]][[1]]@AtAge$Number[1,1,,], 1, sum) +  apply(multiHist[[2]][[1]]@AtAge$Number[1,1,,], 1, sum)

plot(rec$Yr, rec$Rec)
lines(rec$Yr, SimRec)
cbind(rec$Yr, rec$Rec, SimRec, rec$Rec-SimRec)

SB # year 1951
rec # year 1951

# 1951
replist$timeseries %>% filter(Yr==1951) %>% select(SpawnBio, Recruit_0)
sum(multiHist[[1]][[1]]@TSdata$SBiomass[1,2,])


# 1950
replist$timeseries %>% filter(Yr==1950) %>% select(SpawnBio, Recruit_0)
sum(multiHist[[1]][[1]]@TSdata$SBiomass[1,1,])

n_age <- replist$natage %>% filter(Yr==1951, `Beg/Mid`=='B', Sex==1) %>% 
  tidyr::pivot_longer(cols=13:ncol(replist$natage)) %>%
  select(Yr, Sex, Age=name, N=value) %>%
  mutate(Age=as.numeric(Age))

sum(n_age$N * MOM@cpars$Female$SPN_1$Wt_age[1,,1] * MOM@cpars$Female$SPN_1$Mat_age[1,,1])
sum(rowSums(multiHist[[1]][[1]]@AtAge$Number[1,,2,]) * MOM@cpars$Female$SPN_1$Wt_age[1,,1] * MOM@cpars$Female$SPN_1$Mat_age[1,,1])

# 


tt N_SS %>% filter(Age==0, Yr==yrs[2])
N_Sim %>% filter(Age==0, Yr==yrs[2])








replist$timeseries$SpawnBio[1]

replist$SBzero

ss1 <- N_SS %>% filter(Sex==1)

sim1 <- N_OM %>% filter(Sex==1, Sim==1) 

plot(ss1$Yr, ss1$N)
lines(ss1$Yr, sim1$N, col='blue')


# why are the Fs different?
N_SS <- replist$natage  %>% filter(Yr %in% OM_years, `Beg/Mid`=="B") %>% 
  tidyr::pivot_longer(cols=13:ncol(replist$natage))

replist$SBzero
multiHist[[1]][[1]]@Ref$ReferencePoints$SSB0
tt <- N_SS %>% filter(Yr==OM_years[1], Sex==1)

endgrowth <- replist$endgrowth %>% filter(Sex==1)
wt <- endgrowth$Wt_Beg
mat <- endgrowth$Len_Mat * endgrowth$Age_Mat 

replist$wtatage$Fleet %>% unique()

fl <- -2
wt_age_emp <- replist$wtatage %>% filter(Sex==1, Yr==1970)  %>% tidyr::pivot_longer(cols=7:ncol(replist$wtatage))

wt_age_emp <- wt_age_emp %>% filter(Fleet==fl)

sum(tt$value * wt * mat)
sum(tt$value * wt_age_emp$value * mat)
replist$SBzero

nss <- replist$natage  %>% filter(`Beg/Mid`=="B")%>% 
  tidyr::pivot_longer(cols=13:ncol(replist$natage))

t1 <- nss %>% filter(Yr==1968, Sex==1)
t2 <- nss %>% filter(Yr==OM_years[1], Sex==1)

sum(t1$value * wt * mat)
sum(t2$value * wt * mat)
replist$timeseries %>% filter(Yr==1968)

ns <- replist$natage_annual_1_no_fishery %>% filter(Yr==1970, Sex==1) 


rowSums(multiHist[[1]][[1]]@AtAge$Number[1,,1,])
rowSums(multiHist[[1]][[1]]@AtAge$Biomass[1,,1,])
rowSums(multiHist[[1]][[1]]@AtAge$SBiomass[1,,1,])


N_sim <- apply(multiHist[[1]][[1]]@AtAge$Number, 1:3, sum)
mm <- rep(0,49)
for (i in 1:49) {
  tt <- N_SS %>% filter(Yr==OM_years[i], Sex==1)
  tt$name <- as.numeric(tt$name)
  plot(tt$name, tt$value)
  lines(tt$name, N_sim[1,,i])
  mm[i] <- min(abs((tt$value/N_sim[1,,i])))
}

tt <- N_SS %>% filter(Yr==OM_years[i], Sex==1)
tt$name <- as.numeric(tt$name)
plot(tt$name, tt$value)
lines(tt$name, N_sim[1,,i])
min(abs((tt$value/N_sim[1,,i])))


parallel=TRUE; silent=FALSE

Yrs <- replist$startyr:replist$endyr
SS_N <- replist$natage %>% filter(Yr%in%Yrs) %>% tidyr::pivot_longer(cols=13:ncol(replist$natage))
SS_N$Age <- as.numeric(SS_N$name)

sex <- 2
tt <- SS_N %>% filter(Yr==Yrs[1], Sex==sex, `Beg/Mid`=='B')
p <- sex
simAge <- rowSums(multiHist[[p]][[1]]@AtAge$Number[1,,1,])
plot(tt$Age, tt$value)
lines(tt$Age, rowSums(multiHist[[p]][[1]]@AtAge$Number[1,,1,]))

multiHist[[p]][[1]]@TSdata$Find

ind <- 2:nrow(tt)
ind1 <- ind-1
-log(tt$value[ind]/tt$value[ind1])

MOM@cpars$Female$Com.Live$M_ageArray

tt$value
Ages <- 0:length(tt$value)
53.778*exp(-0.24*Ages)
simAge[1]*exp(-0.24*Ages)



C_SS <- cbind(replist$timeseries[, 1:4], rowSums(replist$timeseries[, startsWith(names(replist$timeseries), "dead(B):")], na.rm = TRUE))
C_SS <- aggregate(C_SS[, 5], list(Year = C_SS$Yr), sum)
C_SS <- C_SS[C_SS$Year %in% OM_years, 2]

ns <- length(multiHist)
nf <- length(multiHist[[1]])
C_OM <- matrix(0, nrow=nsim, ncol=n.yrs)
for (p in 1:ns) {
  for (fl in 1:nf) {
    C_OM <- C_OM + apply(multiHist[[p]][[fl]]@TSdata$Removals, 1:2, sum)
  }
}

ylim_cat <- c(0, 1.1 * max(C_SS, C_OM))
matplot(OM_years, t(C_OM), xlab = year_lab, ylab = "Removals", ylim = ylim_cat, pch = 1, col = "black", typ = "o")
lines(OM_years, C_SS, col = "red", lwd = 3)
abline(h = 0, col = "grey")
