# This file is auto-generated by build_tools/write_class_definitions.R
# Do not edit by hand


#' @slot Name NA
#' @slot TACFrac NA
#' @slot TACSD NA
#' @slot TAEFrac NA
#' @slot TAESD NA
#' @slot SizeLimFrac NA
#' @slot SizeLimSD NA
