# This file is auto-generated by build_tools/write_class_definitions.R
# Do not edit by hand


#' @slot Name Name of the MSE object. Single value. Character string
#' @slot nyears The number of years for the historical simulation. Single
#'  value. Positive integer
#' @slot proyears The number of years for the projections - closed loop
#'  simulations. Single value. Positive integer
#' @slot nMPs Number of management procedures simulation tested. Single value.
#'  Positive integer.
#' @slot MPs The names of the MPs that were tested. Vector of length nMPs.
#'  Character strings.
#' @slot nsim Number of simulations. Single value. Positive integer
#' @slot OM Operating model parameters (last historical year used for
#'  time-varying parameters). Data.frame with `nsim` rows
#' @slot Obs Observation parameters (last historical year used for time-varying
#'  parameters). Data.frame with `nsim` rows
#' @slot SB_SBMSY Simulated spawning biomass relative to spawning BMSY over the
#'  projection. An array with dimensions: nsim, nMPs, proyears. Non-negative real
#'  numbers
#' @slot F_FMSY Simulated fishing mortality rate relative to FMSY over the
#'  projection. An array with dimensions: nsim, nMPs, proyears. Non-negative real
#'  numbers
#' @slot N Simulated total numbers over the projection. An array with
#'  dimensions: nsim, maxage+1, nMPs, proyears, nareas. Non-negative real numbers.
#' @slot B Simulated stock biomass over the projection. An array with
#'  dimensions: nsim, nMPs, proyears. Non-negative real numbers
#' @slot SSB Simulated spawning stock biomass over the projection. An array
#'  with dimensions: nsim, nMPs, proyears. Non-negative real numbers
#' @slot VB Simulated vulnerable biomass over the projection. An array with
#'  dimensions: nsim, nMPs, proyears. Non-negative real numbers
#' @slot FM Simulated fishing mortality rate over the projection. An array with
#'  dimensions: nsim, nMPs, proyears. Non-negative real numbers
#' @slot SPR Currently not used.
#' @slot C Simulated catches (landings) over the projection. An array with
#'  dimensions: nsim, nMPs, proyears. Non-negative real numbers
#' @slot Removals Simulated removals (catch + discards) over the projection. An
#'  array with dimensions: nsim, nMPs, proyears. Non-negative real numbers
#' @slot Effort Simulated relative fishing effort in the projection years. An
#'  array with dimensions: nsim, nMPs, proyears. Non-negative real numbers
#' @slot TAC Simulated Total Allowable Catch prescribed by MPs. An array with
#'  dimensions: nsim, nMPs, proyears. Non-negative real numbers
#' @slot TAE Simulated Total Allowable Effort prescribed by MPs. An array with
#'  dimensions: nsim, nMPs, proyears. Non-negative real numbers
#' @slot BioEco Named list with bio-economic output Only used if bio-economic
#'  parameters are included in OM
#' @slot RefPoint Named list of annual MSY reference points MSY, FMSY, and
#'  SBMSY. Array with dimensions: nsim, nMPs, nyears+proyears. Will be the same as
#'  `Hist@Ref$ByYear` unless selectivity is changed by MP
#' @slot Hist Information from the historical spool-up period. Object of class
#'  `Hist`
#' @slot PPD Posterior predictive data. List of `Data` objects at the end of
#'  the projection period (length `nMPs`)
#' @slot Misc Miscellaneous output
