# This file is auto-generated by build_tools/write_class_definitions.R
# Do not edit by hand


#' @slot Name NA
#' @slot Cobs NA
#' @slot Cbiascv NA
#' @slot CAA_nsamp NA
#' @slot CAA_ESS NA
#' @slot CAL_nsamp NA
#' @slot CAL_ESS NA
#' @slot Iobs NA
#' @slot Ibiascv NA
#' @slot Btobs NA
#' @slot Btbiascv NA
#' @slot beta NA
#' @slot LenMbiascv NA
#' @slot Mbiascv NA
#' @slot Kbiascv NA
#' @slot t0biascv NA
#' @slot Linfbiascv NA
#' @slot LFCbiascv NA
#' @slot LFSbiascv NA
#' @slot FMSYbiascv NA
#' @slot FMSY_Mbiascv NA
#' @slot BMSY_B0biascv NA
#' @slot Irefbiascv NA
#' @slot Brefbiascv NA
#' @slot Crefbiascv NA
#' @slot Dbiascv NA
#' @slot Dobs NA
#' @slot hbiascv NA
#' @slot Recbiascv NA
