# Test import halibut



SSdir <- 'G:/My Drive/1_PROJECTS/CDFW_Multi_Fleet/Halibut/SS3/North'


devtools::load_all()

MOM <- SS2MOM(SSdir, nsim=3)


np <- 2
nf <- 5
# add to SS2MOM
for (p in 1:np) {
  for (f in 1:nf) {
    # retL is passed - can these by empty then?
    MOM@cpars[[p]][[f]]$LR5 <- MOM@cpars[[p]][[f]]$LFR <- rep(0, MOM@nsim)
    MOM@cpars[[p]][[f]]$Rmaxlen <- rep(1, MOM@nsim)
    # add to SS2MOM - make FALSE by default
    MOM@Fleets[[p]][[f]]@MPA <- FALSE 
  }
}


multiHist <- SimulateMOM(MOM, parallel = TRUE)




# 3. understand why year 2 age structure is different

# --- Compare with SS3 ---

# ---- Compare N-at-Age in initial year ----

p <- 1
yr <- 2
SS <- replist$natage %>% dplyr::filter(Sex==p, Yr==mainyrs[yr], `Beg/Mid`=='B') %>%
  dplyr::select(13:38)
Sim <- rowSums(multiHist[[p]][[1]]@AtAge$Number[1,,1,])

df <- data.frame(SS=as.numeric(SS[1,]), Sim=Sim) %>% round(2)
df[,2]/df[,1]

plot(as.numeric(SS[1,]), ylim=c(0, max(Sim)))
lines(Sim)

# recruitment yr 2
Sim[1]
SS[1]


# is spawning biomass the same?
rowSums(multiHist[[p]][[1]]@TSdata$SBiomass[1,1:2,])

replist$timeseries %>% dplyr::filter(Yr %in% mainyrs[1:2]) %>% 
  dplyr::select(SpawnBio)



# SB0 aren't the same!
multiHist[[p]][[1]]@Ref$ReferencePoints$SSB0[1]

replist$SBzero



# ---- Compare Historical Biomass ----
SS_DF <- data.frame(Year=replist$timeseries$Yr,
                    B=replist$timeseries$Bio_all,
                    SSB=replist$timeseries$SpawnBio)
SS_DF <- SS_DF %>% dplyr::filter(Year %in% mainyrs)

Sim_DF <- data.frame(Year=mainyrs,
                     B=rowSums(multiHist[[1]][[1]]@TSdata$Biomass[1,,] + 
                                 multiHist[[2]][[1]]@TSdata$Biomass[1,,]),
                     SSB=rowSums(multiHist[[p]][[1]]@TSdata$SBiomass[1,,]))


SS_DF
SS_DF$SSB[nrow(SS_DF)]/replist$SBzero
Sim_DF$SSB[nrow(Sim_DF)]/replist$SBzero
Sim_DF$SSB[nrow(Sim_DF)]/multiHist[[p]][[1]]@Ref$ReferencePoints$SSB0[1]



# Total Biomass
plot(SS_DF$Year, SS_DF$B, ylim=c(0, max(c(SS_DF$B, Sim_DF$B))), type="l")
lines(Sim_DF$Year, Sim_DF$B, col='blue')

# Spawning Biomass
plot(SS_DF$Year, SS_DF$SSB, ylim=c(0, max(c(SS_DF$SSB, Sim_DF$SSB))), type="l")
lines(Sim_DF$Year, Sim_DF$SSB, col='blue')


# Spawning Biomass

plot(SS_DF$Year, SS_DF$SSB, ylim=c(0, max(c(SS_DF$SSB, Sim_DF$SSB))), type="l")
lines(Sim_DF$Year, Sim_DF$SSB, col='blue')



replist <- SS_import(SSdir, silent=TRUE)
mainyrs <- replist$startyr:replist$endyr
nyears <- length(mainyrs)



initSB <- replist$timeseries %>% dplyr::filter(Yr==mainyrs[1]) %>%
  dplyr::select(SpawnBio)


terminalSB <- replist$timeseries %>% dplyr::filter(Yr==mainyrs[length(mainyrs)]) %>%
  dplyr::select(SpawnBio)

SB0 <- replist$timeseries %>% dplyr::filter(Era=="VIRG") %>%
  dplyr::select(SpawnBio)

initD <- rep(initSB$SpawnBio/SB0$SpawnBio, 2)
replist$current_depletion



# TODO:
#
# SimulateMOM:
# - add messages for sampling, stock, fleet, etc 
# - check time estimates for halibut 












# ---- Compare Catch by Sex and Fleet -----
nstock <- length(MOM@Stocks)
nfleet <- length(MOM@Fleets[[1]])

List <- list()
count <- 0
sim <- 1
for (s in 1:nstock) {
  for (f in 1:nfleet) {
    count <- count+1
    SS <- MOM@cpars[[s]][[f]]$Data@Cat[1,]
    Sim <- rowSums(multiHist[[s]][[f]]@TSdata$Landings[sim,,])
    Catch <- data.frame(Source=c(rep('SS', nyears), rep('Sim', nyears)),
                        Catch=c(SS, Sim))
    List[[count]] <- data.frame(Year=rep(mainyrs,2), Catch, Stock=s, Fleet=f)
    
  }
}

CatchDF <- do.call('rbind', List)

library(ggplot2)

ggplot(CatchDF, aes(x=Year, y=Catch, color=Source)) +
  facet_wrap(Stock~Fleet, scales="free", ncol=5) +
  geom_line() + theme_classic()


st <- 2
tt <- CatchDF %>% dplyr::filter(Year==2019) %>% 
  dplyr::group_by(Source) %>%
  dplyr::summarise(catchfrac=sum(Catch))

plot(MOM@CatchFrac[[st]][1,])
lines(tt$catchfrac)

replist$wtatage  

s <- 1
f <- 3
sim <- CatchDF %>% dplyr::filter(Stock==s, Fleet==f, Source=="Sim")
ss <- CatchDF %>% dplyr::filter(Stock==s, Fleet==f, Source=="SS")

plot(sim$Catch/ss$Catch, type="b")


replist <- SS_import(SSdir)

nsim = 48; proyears = 50; reps = 1; maxF = 3; seed = 1; interval = 1; pstar = 0.5;
Obs = Generic_Obs; Imp = Perfect_Imp; silent = FALSE;
Name = "MOM generated by SS2MOM"; Source = "No Source provided"




