
#' Compare SS3 and OM fishery dynamics
#'
#' Generates plots of timeseries of total Number and total Biomass for
#' each stock for users to visually compare the fishery dynamics from the two
#' models. 
#' 
#' The fishery dynamics generated by [Simulate()] should match those from
#' the `SS3` output. If there are significant differences, this indicates either 
#' a problem with the OM import process or a mismatch in the population dynamics 
#' models.
#'
#' @param SSDir Character string giving the path to a directory containing SS3
#'   output files, or a list returned by [ImportSSReport()].
#' @param Hist A `hist-class` or `om-class` object. If an `om-class` object is
#'   supplied to `CompareSS()`, [Simulate()] is called automatically before
#'   comparison.
#' @param sim Integer. Simulation index used to select both the SS3 report
#'   element and the OM simulation row. Default `1`. Only used where
#'   [ImportSSReport()] is applied to multiple SS3 output directories.
#' @param silent Logical. Passed to [ImportSSReport()] and [Simulate()] to
#'   suppress console output. Default `FALSE`.
#' @param ... Additional arguments forwarded to [ImportSSReport()].
#'
#' @return
#' - `CompareSS()` returns `NULL` invisibly (called for its side-effects).
#' - `CompareSS_Number()` and `CompareSS_Biomass()` each print a [ggplot2::ggplot()]
#'   object and return the combined `data.frame` of OM and SS3 values invisibly,
#'   with columns `Year`, `Value`, `Stock`, and `Model`.
#'
#' @seealso [ImportSSReport()], [Simulate()], [Number()], [Biomass()]
#' @export
CompareSS <- function(SSDir, Hist, sim = 1, silent = FALSE, ...) {
  RepList <- ImportSSReport(SSDir, silent = silent, ...)
  
  CheckClass(Hist, c('hist', 'om'), 'Hist')
  if (inherits(Hist, 'om'))
    Hist <- Simulate(Hist, 
                     DoDynamicUnfished = FALSE,
                     DoRefLandings     = FALSE,
                     DoRefRemovals     = FALSE,
                     DoConditionObs    = FALSE,
                     DoGenerateData    = FALSE,
                     DoMSYRefs         = FALSE,
                     silent = silent)
  
  CompareSS_Number(RepList, Hist, sim)
  CompareSS_Biomass(RepList, Hist, sim)
  
  invisible(NULL)
}



#' @export
#' @rdname CompareSS
CompareSS_Number <- function(SSDir, Hist, sim = 1, silent=FALSE, ...) {
  .CompareSS_internal(
    SSDir   = SSDir,
    Hist      = Hist,
    sim       = sim,
    silent    = silent,
    om_fn     = Number,
    ss_table  = "natage",
    y_label   = "Number", 
    ...
  )
}

#' @export
#' @rdname CompareSS
CompareSS_Biomass <- function(SSDir, Hist, sim = 1, silent=FALSE, ...) {
  .CompareSS_internal(
    SSDir   = SSDir,
    Hist      = Hist,
    sim       = sim,
    silent    = silent,
    om_fn     = Biomass,
    ss_table  = "batage",
    y_label   = "Biomass", 
    ...
  )
}

.CompareSS_internal <- function(SSDir, Hist, sim, silent, om_fn, ss_table, y_label, ...) {
  
  RepList <- ImportSSReport(SSDir, silent = silent, ...)
  CheckClass(Hist, 'hist', 'Hist')
  
  replist    <- RepList[[sim]]
  HistYears  <- Years(Hist@OM, 'H')
  AgeClasses <- GetSSAgeClasses(replist)
  
  OM_Value <- om_fn(Hist, df = TRUE) |>
    dplyr::mutate(Model = 'OM') |>
    dplyr::filter(Sim == sim) |>
    dplyr::arrange(Stock, Year) |>
    dplyr::select(Year, Value, Stock, Model)
  
  SS_Value <- replist[[ss_table]] |>
    dplyr::filter(Yr %in% HistYears, `Beg/Mid` == 'B') |>
    dplyr::rename(Year = Yr, Stock = Sex) |>
    tidyr::pivot_longer(cols = as.character(AgeClasses)) |>
    dplyr::group_by(Stock, Year, Seas) |>
    dplyr::summarise(Value = sum(value), Model = 'SS3', .groups = 'drop') |>
    dplyr::mutate(
      Stock = dplyr::case_match(Stock, 1 ~ 'Female', 2 ~ 'Male')
    ) |>
    dplyr::select(Stock, Year, Value, Model) |>
    dplyr::arrange(Stock, Year) |>
    dplyr::mutate(
      Year  = OM_Value$Year,
      Stock = OM_Value$Stock
    )
  
  df <- dplyr::bind_rows(OM_Value, SS_Value) |>
    dplyr::select(Year, Value, Stock, Model) |>
    dplyr::arrange(Year)
  
  p <- ggplot2::ggplot(
    df,
    ggplot2::aes(x = Year, y = Value, color = Model, shape = Model, linetype = Model)
  ) +
    ggplot2::facet_grid(~Stock) +
    ggplot2::geom_line() +
    ggplot2::geom_point() +
    ggplot2::expand_limits(y = 0) +
    ggplot2::labs(y = y_label) +
    theme_bw()
  
  print(p)
  invisible(df)
}

