
#' Compare SS3 and OM fishery dynamics
#'
#' Generates plots of timeseries of total Number, total Biomass, Landings, and
#' Discards for each stock/fleet for users to visually compare the fishery
#' dynamics from the two models.
#'
#' The fishery dynamics generated by [Simulate()] should match those from
#' the `SS3` output. If there are significant differences, this indicates either
#' a problem with the OM import process or a mismatch in the population dynamics
#' models.
#'
#' @param SSDir Character string giving the path to a directory containing SS3
#'   output files, or a list returned by [ImportSSReport()].
#' @param Hist A `hist-class` or `om-class` object. If an `om-class` object is
#'   supplied to `CompareSS()`, [Simulate()] is called automatically before
#'   comparison.
#' @param sim Integer. Simulation index used to select both the SS3 report
#'   element and the OM simulation row. Default `1`. Only used where
#'   [ImportSSReport()] is applied to multiple SS3 output directories.
#' @param plot Logical. Plot the timeseries for the `OM` and `SS3` output? If
#'   `plot = FALSE` (default) the plots are only printed if MARE exceeds
#'   `thresh` in some years -- see [CompareBAM()] for the same convention.
#' @param thresh Numeric. Mean absolute relative error (MARE, as a
#'   percentage) threshold above which a series is flagged and plotted.
#'   Default `1`.
#' @param save_plots Logical. If `TRUE`, diagnostic plots are written as PNG
#'   files to `file.path(outdir, Stock)`. Default `FALSE`.
#' @param outdir Character. Base directory for saved plots. Defaults to
#'   `"figures/diagnostics/SS3"`.
#' @param width,height Numeric. Width/height (inches) passed to
#'   [ggplot2::ggsave()]. If `NULL` (default), sized automatically from the
#'   number of facet panels -- see [CompareBAM()].
#' @param silent Logical. Passed to [ImportSSReport()] and [Simulate()] to
#'   suppress console output. Default `FALSE`.
#' @param ... Additional arguments forwarded to [ImportSSReport()].
#'
#' @return
#' - `CompareSS()` invisibly returns a named list with elements `Stock`,
#'   `Recruits`, `Number`, `Biomass`, `Landings`, and `Discards`, each (other
#'   than `Stock`) a list with elements `df`, `MARE`, and `plot` -- the same
#'   shape as [CompareBAM()].
#' - `CompareSS_Number()` and `CompareSS_Biomass()` each print a [ggplot2::ggplot()]
#'   object and return the combined `data.frame` of OM and SS3 values invisibly,
#'   with columns `Year`, `Value`, `Stock`, and `Model`.
#' - `CompareSS_Landings()` and `CompareSS_Discards()` each print a
#'   [ggplot2::ggplot()] object and return the combined `data.frame` invisibly,
#'   with columns `Year`, `Fleet`, `Value`, and `Model`. Values are in kg
#'   (SS3 `retain(B)` / `dead(B)` timeseries converted from metric tons;
#'   OM from [Landings()] / [Discards()]).
#'
#' @seealso [ImportSSReport()], [Simulate()], [Number()], [Biomass()],
#'   [Landings()], [Discards()], [CompareBAM()]
#' @export
CompareSS <- function(SSDir, Hist, sim = 1, plot = FALSE, thresh = 1,
                      save_plots = FALSE, outdir = 'figures/diagnostics/SS3',
                      width = NULL, height = NULL, silent = FALSE, ...) {
  RepList <- ImportSSReport(SSDir, silent = silent, ...)

  .CheckClass(Hist, c('hist', 'om'), 'Hist')
  if (inherits(Hist, 'om'))
    Hist <- Simulate(Hist,
                     DoDynamicUnfished = FALSE,
                     DoRefLandings     = FALSE,
                     DoRefRemovals     = FALSE,
                     DoConditionObs    = FALSE,
                     DoGenerateData    = FALSE,
                     DoMSYRefs         = FALSE,
                     silent = silent)

  Out <- list()
  complex_nm   <- names(Hist@OM@Complexes)[1]
  Out$Stock    <- if (!is.null(complex_nm) && !is.na(complex_nm)) complex_nm else Hist@OM@Stock[[1]]@Name
  Out$Recruits <- .CompareSSRecruitsImpl(RepList, Hist, sim)
  Out$Number   <- .CompareSSInternal(RepList, Hist, sim, om_fn = Number,
                                      ss_table = 'natage', y_label = 'Number')
  Out$Biomass  <- .CompareSSInternal(RepList, Hist, sim, om_fn = Biomass,
                                      ss_table = 'batage', y_label = 'Biomass')
  Out$Landings <- .CompareSSCatchInternal(RepList, Hist, sim, catch_type = 'landings')
  Out$Discards <- .CompareSSCatchInternal(RepList, Hist, sim, catch_type = 'discards')

  figdir <- file.path(outdir, Out$Stock)

  Out <- .ComparePrintPlot(Out, 'Recruits', title = Out$Stock, plot = plot, thresh = thresh,
                            save_plots = save_plots, figdir = figdir, width = width, height = height)
  Out <- .ComparePrintPlot(Out, 'Number', title = Out$Stock, plot = plot, thresh = thresh,
                            save_plots = save_plots, figdir = figdir, width = width, height = height)
  Out <- .ComparePrintPlot(Out, 'Biomass', title = Out$Stock, plot = plot, thresh = thresh,
                            save_plots = save_plots, figdir = figdir, width = width, height = height)
  Out <- .ComparePrintPlot(Out, 'Landings', title = Out$Stock, plot = plot, thresh = thresh,
                            save_plots = save_plots, figdir = figdir, width = width, height = height)
  Out <- .ComparePrintPlot(Out, 'Discards', title = Out$Stock, plot = plot, thresh = thresh,
                            save_plots = save_plots, figdir = figdir, width = width, height = height)

  invisible(Out)
}

#' @export
#' @rdname CompareSS
CompareSS_Number <- function(SSDir, Hist, sim = 1, silent=FALSE, ...) {
  RepList <- ImportSSReport(SSDir, silent = silent, ...)
  .CheckClass(Hist, 'hist', 'Hist')
  res <- .CompareSSInternal(RepList, Hist, sim, om_fn = Number,
                             ss_table = 'natage', y_label = 'Number')
  .PrintCompareSsPlot(res$df, 'Number')
  invisible(res$df)
}

#' @export
#' @rdname CompareSS
CompareSS_Biomass <- function(SSDir, Hist, sim = 1, silent=FALSE, ...) {
  RepList <- ImportSSReport(SSDir, silent = silent, ...)
  .CheckClass(Hist, 'hist', 'Hist')
  res <- .CompareSSInternal(RepList, Hist, sim, om_fn = Biomass,
                             ss_table = 'batage', y_label = 'Biomass')
  .PrintCompareSsPlot(res$df, 'Biomass')
  invisible(res$df)
}

#' @export
#' @rdname CompareSS
CompareSS_Landings <- function(SSDir, Hist, sim = 1, silent = FALSE, ...) {
  RepList <- ImportSSReport(SSDir, silent = silent, ...)
  .CheckClass(Hist, 'hist', 'Hist')
  res <- .CompareSSCatchInternal(RepList, Hist, sim, catch_type = 'landings')
  if (is.null(res)) return(invisible(NULL))
  .PrintCompareSsPlot(res$df, 'Landings')
  invisible(res$df)
}

#' @export
#' @rdname CompareSS
CompareSS_Discards <- function(SSDir, Hist, sim = 1, silent = FALSE, ...) {
  RepList <- ImportSSReport(SSDir, silent = silent, ...)
  .CheckClass(Hist, 'hist', 'Hist')
  res <- .CompareSSCatchInternal(RepList, Hist, sim, catch_type = 'discards')
  if (is.null(res)) return(invisible(NULL))
  .PrintCompareSsPlot(res$df, 'Discards')
  invisible(res$df)
}

.PrintCompareSsPlot <- function(df, y_label) {
  has_fleet <- 'Fleet' %in% names(df)
  has_stock <- !has_fleet && 'Stock' %in% names(df)

  p <- ggplot2::ggplot(
    df,
    ggplot2::aes(x = .data$Year, y = .data$Value, color = .data$Model,
                shape = .data$Model, linetype = .data$Model)
  ) +
    ggplot2::geom_line() +
    ggplot2::geom_point() +
    ggplot2::expand_limits(y = 0) +
    ggplot2::labs(y = y_label) +
    theme_bw()

  if (has_fleet) p <- p + ggplot2::facet_wrap(~Fleet, scales = 'free_y')
  if (has_stock) p <- p + ggplot2::facet_grid(~Stock)

  print(p)
  invisible(p)
}

.GetSSTimseriesCatch <- function(replist, HistYears, FishFleets, SSFleetNames, col_prefix) {
  ts <- replist$timeseries |>
    dplyr::filter(Yr %in% HistYears) |>
    dplyr::arrange(Yr, Seas)

  purrr::map2_dfr(FishFleets, SSFleetNames, function(fl, fleet_name) {
    col <- paste0(col_prefix, fl)
    if (!col %in% names(ts))
      return(data.frame(Year = numeric(0), Fleet = character(0), Value = numeric(0)))
    data.frame(Year = HistYears[seq_len(nrow(ts))], Fleet = fleet_name, Value = ts[[col]])
  })
}

.CompareSSCatchInternal <- function(RepList, Hist, sim, catch_type) {

  replist    <- RepList[[sim]]
  HistYears  <- Years(Hist@OM, 'H')

  FishFleets   <- which(replist$IsFishFleet)
  SSFleetNames <- unique(replist$catch$Fleet_Name)[FishFleets]

  catch_units <- replist$catch_units[FishFleets]  # "1" = biomass, "2" = numbers

  retain_df <- .GetSSTimseriesCatch(replist, HistYears, FishFleets, SSFleetNames,
                                     col_prefix = 'retain(B):_')
  dead_df   <- .GetSSTimseriesCatch(replist, HistYears, FishFleets, SSFleetNames,
                                     col_prefix = 'dead(B):_')

  if (nrow(retain_df) == 0 || nrow(dead_df) == 0) {
    cli::cli_alert_warning('SS3 timeseries retain(B) / dead(B) columns not found; cannot compare catch.')
    return(invisible(NULL))
  }

  unit_map <- data.frame(Fleet = SSFleetNames,
                         catch_unit = as.character(catch_units))

  if (catch_type == 'landings') {
    SS_Value <- retain_df
    OM_Value <- Landings(Hist, byFleet = TRUE) |>
      dplyr::filter(Sim == sim) |>
      dplyr::group_by(Year, Fleet) |>
      dplyr::summarise(Value = sum(Value), .groups = 'drop') |>
      dplyr::mutate(Model = 'OM')
  } else {
    SS_Value <- dplyr::left_join(dead_df, retain_df,
                                 by = c('Year', 'Fleet'),
                                 suffix = c('_dead', '_ret')) |>
      dplyr::mutate(Value = Value_dead - Value_ret) |>
      dplyr::select(Year, Fleet, Value)

    if (all(SS_Value$Value == 0, na.rm = TRUE))
      return(invisible(NULL))

    OM_Value <- Discards(Hist, byFleet = TRUE) |>
      dplyr::filter(Sim == sim) |>
      dplyr::group_by(Year, Fleet) |>
      dplyr::summarise(Value = sum(Value), .groups = 'drop') |>
      dplyr::mutate(Model = 'OM')
  }

  SS_Value <- SS_Value |>
    dplyr::left_join(unit_map, by = 'Fleet') |>
    dplyr::select(Year, Fleet, Value) |>
    dplyr::mutate(Model = 'SS3')

  df <- dplyr::bind_rows(OM_Value, SS_Value) |>
    dplyr::arrange(Year, Fleet)

  .CompareMare(df, 'SS3')
}

.CompareSSInternal <- function(RepList, Hist, sim, om_fn, ss_table, y_label) {

  replist    <- RepList[[sim]]
  HistYears  <- Years(Hist@OM, 'H')
  AgeClasses <- .GetSSAgeClasses(replist)
  
  OM_Value <- om_fn(Hist, df = TRUE) |>
    dplyr::mutate(Model = 'OM') |>
    dplyr::filter(Sim == sim) |>
    dplyr::arrange(Stock, Year) |>
    dplyr::select(Year, Value, Stock, Model)
  
  SS_Value <- replist[[ss_table]] |>
    dplyr::filter(Yr %in% HistYears, `Beg/Mid` == 'B') |>
    dplyr::rename(Year = Yr, Stock = Sex) |>
    tidyr::pivot_longer(cols = as.character(AgeClasses)) |>
    dplyr::group_by(Stock, Year, Seas) |>
    dplyr::summarise(Value = sum(value), Model = 'SS3', .groups = 'drop') |>
    dplyr::mutate(
      Stock = dplyr::recode_values(Stock, 1 ~ 'Female', 2 ~ 'Male')
    ) |>
    dplyr::select(Stock, Year, Value, Model) |>
    dplyr::arrange(Stock, Year) |>
    dplyr::mutate(
      Year  = OM_Value$Year,
      Stock = OM_Value$Stock
    )
  
  df <- dplyr::bind_rows(OM_Value, SS_Value) |>
    dplyr::select(Year, Value, Stock, Model) |>
    dplyr::arrange(Year)

  .CompareMare(df, 'SS3')
}

.CompareSSRecruitsImpl <- function(RepList, Hist, sim) {
  replist   <- RepList[[sim]]
  HistYears <- Years(Hist@OM, 'H')

  OM_Value <- Number(Hist, df = TRUE, byAge = TRUE) |>
    dplyr::filter(.data$Sim == sim, .data$Age == min(.data$Age)) |>
    dplyr::group_by(Year) |>
    dplyr::summarise(Value = sum(Value)) |>
    dplyr::mutate(Model = 'OM') |>
    dplyr::select('Year', 'Value', 'Model')

  AgeClasses <- .GetSSAgeClasses(replist)
  minAge     <- as.character(min(AgeClasses))

  if (!minAge %in% names(replist$natage))
    return(NULL)

  birthseas <- .GetSSBirthSeas(replist)

  SS_Value <- replist$natage |>
    dplyr::filter(.data$Yr %in% HistYears, .data$`Beg/Mid` == 'B') |>
    dplyr::rename(Year = 'Yr') |>
    dplyr::group_by(.data$Year, .data$Seas) |>
    dplyr::summarise(Value = sum(.data[[minAge]]), .groups = 'drop') |>
    dplyr::arrange(.data$Year, .data$Seas) |>
    dplyr::mutate(
      Value = ifelse(.data$Seas == birthseas, .data$Value, 0),
      Year  = OM_Value$Year,
      Model = 'SS3'
    ) |>
    dplyr::select('Year', 'Value', 'Model')

  df <- dplyr::bind_rows(OM_Value, SS_Value) |>
    dplyr::arrange(.data$Year)

  .CompareMare(df, 'SS3')
}
