
#' @rdname ImportSS
#' @export
ImportSSReport <- function(SSDir, silent=FALSE, ...) {
  OnExit()
  CheckPackage("r4ss", '1.52.1', "pak::pkg_install('r4ss/r4ss')")
  
  if (!requireNamespace("r4ss", quietly = TRUE)) {
    cli::cli_abort(
      "Download the `r4ss` package to use this function. Install the Github version with: `remotes::install_github(\"r4ss/r4ss\")`", 
      call. = FALSE)
  }
  
  # SSDir is a list - imort 
  if (inherits(SSDir, "list")) {
    
    # already list of SS_output lists
    if (is.list(SSDir[[1]])) {
      names(SSDir) <- seq_along(SSDir)
      return(SSDir)
    }
    
    # return SS_output in a list
    if (!is.null(SSDir$SS_version)) {
      RepList <- list(SSDir)
      names(RepList) <- "1"
      return(RepList)
    }
    
    cli::cli_abort(
      "`SSDir` is a list but does not appear to be generated by `r4ss::SS_output`"
    )
  }
  
  # SSDir is a character vector of directories
  if (!is.character(SSDir)) {
    cli::cli_abort("`SSDir` must be a character vector or an r4ss output list")
  }
  
  ## single directory
  if (length(SSDir) == 1L) {
    RepList <- list(GetSSRepList(SSDir, silent = silent, ...))
    names(RepList) <- "1"
    return(RepList)
  }
    
  ## multiple directories
  has_report <- vapply(
    SSDir,
    function(d) any(grepl("^Report\\.sso", list.files(d))),
    logical(1)
  )
  
  if (any(!has_report)) {
    cli::cli_alert_warning(
      "Warning: SS3 output is not available in {?directory/directories}: {.val {basename(SSDir[!has_report])}}.\nSkipping {?this/these} {?directory/directories} ..."
    )
    SSDir <- SSDir[has_report]
  }
    
  if (length(SSDir) == 0L) {
    return(list())
  }

  RepList <- purrr::map(
    SSDir,
    GetSSRepList,
    silent = TRUE,
    ...,
    .progress = list(
      caller = environment(),
      format = "Reading SS3 Output from {.val {length(SSDir)}} directories {cli::pb_bar} {cli::pb_percent}"
    )
  )
  
  names(RepList) <- seq_along(RepList)
  RepList
  
}

GetSSRepList <- function(SSDir, silent = FALSE, ...) {


  dots <- list(dir = SSDir)
  dots <- list(dir = SSDir, ...)
  if (!any(names(dots) == "covar")) dots$covar <- FALSE
  if (!any(names(dots) == "forecast")) dots$forecast <- FALSE
  if (!any(names(dots) == "printstats")) dots$printstats <- FALSE
  if (!any(names(dots) == "verbose")) dots$verbose <- FALSE
  if (!any(names(dots) == "warn")) dots$warn <- FALSE

  if (!silent) {
    cli::cli_progress_message("Importing SS3 output from {.val {basename(SSDir)}}")
  }

  replist <- try(do.call(r4ss::SS_output, dots), silent = TRUE)

  if (!silent) {
    cli::cli_progress_done()
  }

  if (is.character(replist)) {
    cli::cli_abort(c("`r4ss::SS_output` function returned an error.",
      "x" = replist
    ), call. = FALSE)
  }

  replist
}
