
#' @rdname ImportSS
#' @export
ImportSSReport <- function(Dir, silent=FALSE, ...) {
  OnExit()
  CheckPackage("r4ss", '1.52.1', "pak::pkg_install('r4ss/r4ss')")
  
  if (!requireNamespace("r4ss", quietly = TRUE)) {
    cli::cli_abort("Download the `r4ss` package to use this function. It is recommended to install the Github version with: `remotes::install_github(\"r4ss/r4ss\")`", call. = FALSE)
  }
  
  if (inherits(Dir, "list")) {
    if (inherits(Dir[[1]], "list")) {
      names(Dir) <- 1:length(Dir)
      return(Dir)
    } else if (!is.null(Dir$SS_version)) {
      RepList <- list(Dir)
      names(RepList) <- 1:length(RepList)
      return(RepList)
    } else {
      cli::cli_abort("`Dir` is a list but does not appear to be generated by `r4ss::SS_output`")
    }
  }

  if (inherits(Dir, "character")) {
    if (length(Dir) > 1) {
      #
      AllSSFiles <- lapply(Dir, list.files)
      ReportExists <- lapply(AllSSFiles, function(x) sum(grepl("^Report.sso", x))) |>
        unlist()
      ind <- which(ReportExists < 1)
      if (length(ind) > 0) {
        cli::cli_alert_warning("Warning: SS3 output is not available in {?directory/directories}: {.val {basename(x[ind])}}. \nSkipping {?this/these} {?directory/directories} ...")
        Dir <- Dir[-ind]
      }


      # TODO parallel
      # THIS ISN'T CORRRECT = very slow and doesn't use progress bar
      # see https://furrr.futureverse.org/articles/progress.html#introduction
      # if (parallel) {
      #   if (!silent)
      #     cli::cli_alert('Reading SS3 Output from {.val {length(x)}} directories')
      #   workers <- future::availableCores()/2
      #   future::plan('multisession', workers=workers)
      #   p <- progressr::progressor(steps = length(x))
      #
      #   RepList <-  furrr::future_map(x, ~{
      #     p()
      #     GetSSRepList(.x, silent=TRUE, ...)
      #   })
      #
      # } else {
      #   RepList <- purrr::map(x, \(Dir) GetSSRepList(Dir, silent=TRUE, ...),
      #                         .progress=  list(
      #                           caller = environment(),
      #                           format =  'Reading SS3 Output from {.val {length(x)}} directories {cli::pb_bar} {cli::pb_percent}')
      #   )
      # }

      RepList <- purrr::map(Dir, \(Dir) GetSSRepList(Dir, silent = TRUE, ...),
        .progress = list(
          caller = environment(),
          format = "Reading SS3 Output from {.val {length(Dir)}} directories {cli::pb_bar} {cli::pb_percent}"
        )
      )
    } else {
      RepList <- list(GetSSRepList(Dir, silent, ...))
      names(RepList) <- 1:length(RepList)
      return(RepList)
    }
  }
}

GetSSRepList <- function(Dir, silent = FALSE, ...) {


  dots <- list(dir = Dir)
  dots <- list(dir = Dir, ...)
  if (!any(names(dots) == "covar")) dots$covar <- FALSE
  if (!any(names(dots) == "forecast")) dots$forecast <- FALSE
  if (!any(names(dots) == "printstats")) dots$printstats <- FALSE
  if (!any(names(dots) == "verbose")) dots$verbose <- FALSE
  if (!any(names(dots) == "warn")) dots$warn <- FALSE

  if (!silent) {
    cli::cli_progress_message("Importing SS3 output from {.val {basename(Dir)}}")
  }

  replist <- try(do.call(r4ss::SS_output, dots), silent = TRUE)

  if (!silent) {
    cli::cli_progress_done()
  }

  if (is.character(replist)) {
    cli::cli_abort(c("`r4ss::SS_output` function returned an error.",
      "x" = replist
    ), call. = FALSE)
  }

  replist
}
