#' Generate Historical Size Composition Data
#'
#' Internal function to generate simulated historical size composition data
#' (landings or discards) when real observations are not available.
#'
#' @param x Integer index of the simulation replicate.
#' @param Data Existing `data` object from `OM@Data`.
#' @param Hist A `hist` class object.
#' @param HistYears Numeric vector of historical years.
#' @param i Integer index of the stock complex.
#' @param stocks Integer vector of stock indices in the complex.
#' @param FleetNames Character vector of fleet names.
#' @param type Character. Either `"LandingsAtSize"` or `"DiscardsAtSize"`.
#'
#' @details
#'
#' ## Early Exit Conditions
#'
#' The function returns `slot(Data, type)` unchanged in three cases:
#'
#' - **Real data exist**: `slot(Data, type)` is already populated
#'   (`!EmptyObject(slot(Data, type))`).
#' - **No observation structure defined**: every fleet's [CompObs()] object
#'   is a default (unconditioned) object, as determined by `isNewObject()`.
#' - **True size compositions are all zero**: `Hist@LandingsAtSize` or
#'   `Hist@DiscardsAtSize` are present but contain no fish, indicating size
#'   composition data were not generated by the operating model.
#'
#' ## True Composition
#'
#' True catch-at-size is extracted from `Hist@LandingsAtSize` or
#' `Hist@DiscardsAtSize` (selected by `type`) for replicate `x`, summed over
#' areas and stocks within the complex, retaining the fleet and size dimensions.
#' The result is normalised to proportions \eqn{\mathbf{q}} within each year
#' and fleet.
#'
#' ## Composition Simulation Model
#'
#' For each fleet and year where `SampleSize > 0`, the Dirichlet concentration
#' vector is constructed as:
#'
#' \deqn{\alpha_b = \mathrm{ESS} \cdot \Theta \cdot q_b \cdot \exp(\mathrm{Shift}_b)}
#'
#' A Dirichlet-Multinomial sample of size `SampleSize` is then drawn via
#' [rDirichletMultinomial()]. Years where `SampleSize` is zero or `NA` are
#' left as `NA` in the output.
#'
#' The slot defaults are:
#'
#' - `ESS`: falls back to `SampleSize` if `NULL`
#' - `Theta`: defaults to `1` if `NULL`, recovering a near-multinomial draw
#' - `Shift`: defaults to zero for all bins if `NULL`, applying no tilt
#'
#' ## Obs Structure
#'
#' Observation parameters are accessed via:
#'
#' ```r
#' Hist@OM@Obs[[i]][[fl]]@LandingsAtSize  # or @DiscardsAtSize
#' ```
#'
#' where `i` is the stock complex index and `fl` the fleet index. The relevant
#' [CompObs()] slots are:
#'
#' - `@SampleSize[sim, t]`: nominal sample size; output counts sum to this value
#' - `@ESS[sim, t]`: effective sample size scaling the concentration vector
#' - `@Theta[sim, t]`: Dirichlet-Multinomial dispersion parameter
#' - `@Shift[sim, t, bin]`: per-bin log-concentration offset
#'
#' See [obs-class] and [CompObs()] for full slot documentation.
#'
#' @return A [compdata-class] object with:
#'
#' - `@Name`: character vector of fleet names
#' - `@Value`: `[nYear x nFleet x nSize]` array of composition counts
#' - `@Classes`: numeric vector of size class midpoints
#'
#' @seealso [CompObs()], [CompData()], [compdata-class], [obs-class],
#'   [rDirichletMultinomial()], [GenHistData_AgeComp()], [GenHistData_Catch()]
#' @keywords internal
GenHistData_SizeComp <- function(x, Data, Hist, HistYears, i, stocks, FleetNames,
                                 type = c('LandingsAtSize', 'DiscardsAtSize')) {
  
  type <- match.arg(type, c('LandingsAtSize', 'DiscardsAtSize'))
  
  # Return real data unchanged if already populated
  if (!EmptyObject(slot(Data, type)))
    return(slot(Data, type))
  
  AllObs <- lapply(Hist@OM@Obs[[i]], slot, type)
  no_obs <- all(unlist(lapply(AllObs, isNewObject)))
  
  # No Obs specified for any fleet — skip simulation
  if (no_obs)
    return(slot(Data, type))
  
  nTS    <- length(HistYears)
  nFleet <- length(FleetNames)
  
  # Aggregate true catch-at-size over stocks and areas: [nSize x nYear x nFleet]
  CatchAtSize <- purrr::map(slot(Hist, type)[stocks], \(stock_level) {
    purrr::map(stock_level, \(catch_n) {
      sim_x <- min(x, dim(catch_n)[1])
      catch_n[sim_x,,,,drop=FALSE] |>
        SumOverArea() |>
        DropDimension('Sim')
    }) |> List2Array('Fleet') 
  }) |> List2Array('Stock') |>
    SumOverStock()
  
  CatchAtSize <- SubsetYear(CatchAtSize, HistYears)
  
  # Exit early if true size compositions are all zero
  if (all(CatchAtSize == 0, na.rm = TRUE))
    return(slot(Data, type))
  
  SizeClasses <- dimnames(CatchAtSize)$Class |> as.numeric()
  nSize       <- length(SizeClasses)
  
  Value <- array(0,
                 dim      = c(nTS, nFleet, nSize),
                 dimnames = list(Year  = HistYears,
                                 Fleet = FleetNames,
                                 Class  = SizeClasses))
  
  # Units <- rep('cm', nFleet)
  
  for (fl in seq_len(nFleet)) {
    CompObs <- slot(Hist@OM@Obs[[i]][[fl]], type)
    if (EmptyObject(CompObs) || is.null(CompObs@SampleSize))
      next()
    
    sim_ss     <- min(x, nrow(CompObs@SampleSize))
    SampleSize <- SubsetYear(CompObs@SampleSize, HistYears)[sim_ss, ]
    
    ESS <- if (!is.null(CompObs@ESS)) {
      sim_ess <- min(x, nrow(CompObs@ESS))
      SubsetYear(CompObs@ESS, HistYears)[sim_ess, ]
    } else {
      SampleSize
    }
    
    Theta <- if (!is.null(CompObs@Theta)) {
      sim_th <- min(x, nrow(CompObs@Theta))
      SubsetYear(CompObs@Theta, HistYears)[sim_th, ]
    } else {
      rep(1, nTS)
    }
    
    hasShift <- !is.null(CompObs@Shift)
    if (hasShift) {
      sim_sh <- min(x, dim(CompObs@Shift)[1])
      Shift  <- SubsetYear(CompObs@Shift, HistYears)[sim_sh,, ]  # [nYear x nBin]
    }
    
    for (yr in seq_len(nTS)) {
      ss  <- SampleSize[yr]
      ess <- ESS[yr]
      th  <- Theta[yr]
      
      if (is.na(ss) || ss == 0) next()
      
      true_n  <- CatchAtSize[, yr, fl]
      total_n <- sum(true_n, na.rm = TRUE)
      if (is.na(total_n) || total_n == 0) next()
      
      q <- true_n / total_n
      
      shift_b <- if (hasShift) Shift[yr, ] else rep(0, nSize)
      alpha   <- ess * th * q * exp(shift_b)
      
      if (any(is.na(alpha)) || sum(alpha) == 0) next()
      
      Value[yr, fl, ] <- rDirichletMultinomial(n = round(ss), alpha = alpha)
    }
  }
  
  CompData         <- new('compdata')
  CompData@Name    <- FleetNames
  CompData@Value   <- Value
  CompData@Classes <- SizeClasses
  # CompData@Units   <- Units
  CompData
}

