
#' Import SS3 Report directories with optional parallel processing
#'
#' @param SSDir Character vector of SS3 report directories, or a pre-parsed
#'   `r4ss::SS_output` list or `RepList` object
#' @param parallel Logical; whether to use parallel processing (default FALSE)
#' @param silent Logical; suppress progress messages (default FALSE)
#' @param ... Additional arguments passed to `r4ss::SS_output` and
#'   `GetSSRepList`
#'
#' @return A named `RepList` object: a list of parsed `r4ss::SS_output` lists,
#'   one per SS3 directory, with integer-character names (`"1"`, `"2"`, ...)
#'
#' @seealso [ImportSS()], [SetupParallel()], [DisableParallel()]
#' @export
ImportSSReport <- function(SSDir, parallel=FALSE, silent=FALSE, ...) {
  OnExit()
  CheckPackage("r4ss", '1.52.1', "pak::pkg_install('r4ss/r4ss')")
  
  # SSDir is already a list 
  if (inherits(SSDir, "list") || inherits(SSDir, "RepList")) {
    
    # already list of SS_output lists
    if (is.list(SSDir[[1]])) {
      names(SSDir) <- seq_along(SSDir)
      return(SSDir)
    }
    
    # return SS_output in a list
    if (!is.null(SSDir$SS_version)) {
      RepList <- list(SSDir)
      names(RepList) <- "1"
      return(RepList)
    }
    
    cli::cli_abort(
      "`SSDir` is a list but does not appear to be generated by `r4ss::SS_output`"
    )
  }
  
  # SSDir is a character vector of directories
  if (!is.character(SSDir)) 
    cli::cli_abort(
      "`SSDir` must be a character vector or an r4ss output list"
      )
  
  ## single directory
  if (length(SSDir) == 1L) {
    RepList        <- list(GetSSRepList(SSDir, silent = silent, ...))
    names(RepList) <- "1"
    class(RepList) <- 'RepList'
    return(RepList)
  }
  
  ## multiple directories
  has_report <- vapply(
    SSDir,
    function(d) any(grepl("^Report\\.sso", list.files(d))),
    logical(1)
  )
  
  if (any(!has_report)) {
    cli::cli_alert_warning(
      "SS3 output not found in {?directory/directories}: \\
       {.val {basename(SSDir[!has_report])}}. \\
       Skipping {?this/these} {?directory/directories} ..."
    )
    SSDir <- SSDir[has_report]
  }
  
  if (length(SSDir) == 0L) 
    return(list())
  
  parallel <- CheckParallel(parallel)
  
  if (!parallel) {
    RepList <- purrr::map(
      SSDir,
      GetSSRepList,
      silent = silent,
      ...,
      .progress = list(
        caller = environment(),
        format = paste0(
          "Reading SS3 output from {.val {length(SSDir)}} ",
          "{?directory/directories} {cli::pb_bar} {cli::pb_percent}"
        )
      )
    )
  } else {
    cli::cli_inform(
      "Starting parallel import of {.val {length(SSDir)}} SS3 directories ..."
    )
    CheckPackage('furrr')
    RepList <- furrr::future_map(
      SSDir,
      GetSSRepList,
      silent = silent,
      ...,
      .options = furrr::furrr_options(
        scheduling = Inf,
        globals     = FALSE,
        packages    = "MSEtool",
        seed        = 101
      )
    )
    cli::cli_alert_success("Parallel import complete.")
  }
  
  names(RepList) <- seq_along(RepList)
  class(RepList) <- 'RepList'
  RepList
  
}

GetSSRepList <- function(SSDir, silent = FALSE, ...) {
  
  dots            <- list(dir = SSDir, ...)
  dots$covar      <- dots$covar       %||% FALSE
  dots$forecast   <- dots$forecast    %||% FALSE
  dots$printstats <- dots$printstats  %||% FALSE
  dots$verbose    <- dots$verbose     %||% FALSE
  dots$warn       <- dots$warn        %||% FALSE
  
  if (!silent) 
    cli::cli_progress_message(
      "Importing SS3 output from {.val {basename(SSDir)}}"
      )
  
  replist <- try(do.call(r4ss::SS_output, dots), silent = TRUE)
  
  if (!silent) 
    cli::cli_progress_done()
  
  if (is.character(replist)) {
    cli::cli_abort(
      c("`r4ss::SS_output` returned an error.", "x" = replist)
    )
  }
  
  replist
}
