
#' Import a Stock Synthesis Model into an Operating Model
#'
#' Import a Stock Synthesis 3 (SS3) model and convert it
#' into an [OM()] object.
#'
#' @details
#' 
#'  `ImportSS()` reads SS3 output files from `SSDir` and constructs an
#' [OM()] object. Biological processes, fleet structure, and historical time series
#' are inferred directly from the SS3 report output and mapped into the
#' corresponding OM slots.
#'
#' * Multiple simulation replicates are supported when multiple SS3 runs are detected.
#' * Optional metadata describing authorship, region, and stock identity are stored in the resulting OM.
#' * By default, the OM is fully populated using `PopulateOM()`.
#' * Set `Populate = FALSE` to return the partially constructed OM.
#'
#' `ImportSSReport()` reads SS3 output generated by Stock Synthesis 3,
#' either from one or more directories or from existing `r4ss` report objects,
#' and returns a standardized list of SS3 report lists.
#'
#' @param SSDir Character string giving the path to a directory containing SS3
#'   output files, a vector of such paths, or a list of SS3 report objects
#'   generated by [ImportSSReport()]
#' @param Name Character string giving the name of the imported operating model.
#' @param nSim Integer specifying the number of simulations. Ignored if
#'   multiple SS3 runs are detected; in that case `nSim` is set to the number
#'   of SS3 runs imported.
#' @param pYear Integer specifying the number of projection years.
#' @param Agency Character string giving the management or scientific agency.
#' @param Author Character string giving the model author(s).
#' @param Email Character string giving the author(s) email address.
#' @param Region Character string describing the geographic region.
#' @param Latitude Numeric vector giving stock latitude(s).
#' @param Longitude Numeric vector giving stock longitude(s).
#' @param Sponsor Character string giving the project sponsor.
#' @param StockName Optional character vector of stock names. Length must match
#'   the number of stocks inferred from the SS3 model.
#' @param CommonName Optional character vector of common names for each stock.
#' @param Species Optional character vector of species names for each stock.
#' @param FleetNames Optional character vector of fleet names. If `NULL`,
#'   fleet names are inferred from SS3 output.
#' @param Interval Integer specifying the number of years between management actions.
#' @param DataLag Integer specifying the observation lag in years.
#' @param MPStartYear Numeric or `NULL`. First calendar year in which MPs are
#'   applied; see [OM()]/[om-class]. Default `NULL`.
#' @param InterimAdvice A `data.frame` or `NULL`. Fixed or stochastic
#'   TAC/Effort values for years before `MPStartYear`; see [OM()]/[om-class].
#'   Default `NULL`.
#' @param LengthUnits Character string giving the physical unit of length
#'   measurements in the SS3 model (e.g., `"cm"`, `"mm"`, `"inch"`; see
#'   [ValidUnits()]). Default `"cm"`.
#' @param WeightUnits Character string giving the physical unit of weight
#'   measurements in the SS3 model (e.g., `"kg"`, `"g"`, `"lb"`; see
#'   [ValidUnits()]). Not reported by SS3/`r4ss`; `"kg"` is the conventional
#'   pairing with `LengthUnits = "cm"`. Default `"kg"`.
#' @param R0Units Numeric scaling factor for unfished recruitment (`R0`) and
#'   related numbers-at-age quantities; see `Units` in [srr-class]. SS3 does
#'   not export the numeric scale of its population numbers (e.g. individuals
#'   vs. thousands) as metadata, so this cannot be inferred and must be
#'   supplied by the user if not `1` (absolute numbers of fish). Default `1`.
#' @param silent Logical; if `TRUE`, suppress informational output during import.
#' @param Populate Logical; if `TRUE` (default), populate the OM using
#'   `PopulateOM()`. If `FALSE`, return the partially constructed OM.
#' @param ... Additional arguments passed to SS3 import functions.
#'
#' @return
#' * `ImportSS()` returns an [om-class] object containing stock, fleet, data,
#'   observation, and allocation components derived from the SS3 model.
#' * `ImportSSReport()` returns a list of SS3 report objects.
#'
#' @section Functions:
#' * `ImportSS()` Convert SS3 output into a fully specified operating
#'   model suitable for management strategy evaluation.
#' * `ImportSSReport()` Read SS3 output from directories or existing
#'   `r4ss` report objects and return a standardized list of SS3 reports.
#'
#' @seealso
#' * [OM()]
#' * [PopulateOM()]
#' * [CompareSS()]
#' * <https://nmfs-ost.github.io/ss3-website/> (Stock Synthesis 3)
#'
#' @export
#'
#' @example man-examples/ImportSS.R
ImportSS <- function(SSDir,
                     Name = "Imported SS3 Model",
                     nSim = 48,
                     pYear = 30,
                     Agency = "",
                     Author = "",
                     Email = "",
                     Region = "",
                     Latitude = numeric(),
                     Longitude = numeric(),
                     Sponsor = "",
                     StockName = NULL,
                     CommonName = NULL,
                     Species = NULL,
                     FleetNames = NULL,
                     Interval = 1,
                     DataLag = 0,
                     MPStartYear = NULL,
                     InterimAdvice = NULL,
                     LengthUnits = "cm",
                     WeightUnits = "kg",
                     R0Units = 1,
                     silent = FALSE,
                     Populate = TRUE,
                     ...) {

  .OnExit()
  RepList   <- ImportSSReport(SSDir, silent = silent, ...)
  nStock    <- RepList[[1]]$nsexes
  YearsList <- .GetSSYears(RepList[[1]], pYear)
  nFleet    <- RepList[[1]]$nfishfleets

  DotsList <- list(...)
  if (!is.null(DotsList$nsim)) nSim <- DotsList$nsim

  if (!silent) {
    cli::cli_h3("Importing OM from {.href [SS3](https://nmfs-ost.github.io/ss3-website/)} Output")
    cli::cli_ul()
    cli::cli_li("{.val {nStock}-sex} and {.val {nFleet}-fleet} model detected.")
    cli::cli_li("Time Steps Per Year: {.val {YearsList$Seasons}}")
    cli::cli_li("Years: {.val {min(YearsList$YearsHist)} - {max(YearsList$YearsHist)}}")
    cli::cli_li("Assuming {.val {LengthUnits}} length, {.val {WeightUnits}} weight, and R0 scale {.val {R0Units}} (not reported by SS3; set `LengthUnits`/`WeightUnits`/`R0Units` to override).")
    cli::cli_end()
  }

  if (length(RepList) > 1) 
    nSim <- length(RepList)
  
  OM <- OM(
    Name = Name,
    Agency = Agency,
    Author = Author,
    Email = Email,
    Region = Region,
    Latitude = Latitude,
    Longitude = Longitude,
    Sponsor = Sponsor,
    Interval = Interval,
    DataLag = DataLag,
    MPStartYear = MPStartYear,
    InterimAdvice = InterimAdvice,
    nSim = nSim,
    nYear = YearsList$nYear,
    pYear = YearsList$pYear,
    CurrentYear = YearsList$CurrentYear,
    Seasons = YearsList$Seasons
  )

  OM@nYear       <- YearsList$nYear
  OM@pYear       <- YearsList$pYear
  OM@CurrentYear <- YearsList$CurrentYear
  OM@Years       <- c(YearsList$YearsHist, YearsList$YearsProj)
  OM@Seasons     <- YearsList$Seasons

  # Stock
  StockName <- .ProcessSSStockName(StockName, nStock)
  
  OM@Stock <- purrr::map(seq_along(StockName), \(st) {
    stock            <- .SS2Stock(st, RepList, YearsList, nSim,
                                 LengthUnits = LengthUnits,
                                 WeightUnits = WeightUnits,
                                 R0Units     = R0Units)
    stock@Name       <- StockName[st]
    stock@CommonName <- CommonName[st]
    stock@Species    <- Species[st]
    stock
  },
  .progress = list(
    type = "iterator",
    format = "Importing Stock Dynamics {cli::pb_bar} {cli::pb_percent}",
    clear = TRUE
  ))
  
  names(OM@Stock) <- StockName

  # Fleet
  OM@Fleet <- MakeNamedList(StockName, list())
  
  FleetNames <- .ProcessSSFleetNames(
    FleetNames,
    SSFleetNames = unique(RepList[[1]]$catch$Fleet_Name)
  )
  
  for (st in seq_along(OM@Fleet)) {
    FleetList <- purrr::map(seq_along(FleetNames), \(fl) {
      .SS2Fleet(
        st, 
        fl,
        RepList,
        YearsList,
        FleetNames,
        Stock = OM@Stock[[st]]
      )
    },
    .progress = list(
      type = "iterator",
      format = "Importing Fleet Dynamics for Stock {.val {StockName[st]}} {cli::pb_bar} {cli::pb_percent}",
      clear = TRUE
    ))
    names(FleetList) <- FleetNames
    OM@Fleet[[st]] <- FleetList
  }

  # Data
  OM@Data <- list(ImportSSData(SSDir       = RepList,
                               Name        = OM@Name,
                               CommonName  = CommonName,
                               Species     = Species,
                               LengthUnits = LengthUnits,
                               silent      = silent
  ))
  names(OM@Data) <- paste(StockName, collapse = " ")
  
  # Obs
  SurveyNames <- OM@Data[[1]]@Survey@Name
  AllFleetNames <- c(FleetNames, SurveyNames) |> unique()
  OM@Obs <- MakeNamedList(names(OM@Data), MakeNamedList(AllFleetNames, new("obs")))
  OM <- .ProcessSurveyObsSelectivity(OM, RepList)

  # OM@Imp - TODO

  # Allocation
  OM <- .ProcessSSAllocation(OM, RepList, StockName, FleetNames)
  OM <- .ProcessEFactor(OM)

  
  # OM@Complexes

  # OM@Relations
  
  if (Populate) {
    out <- try(PopulateOM(OM), silent = TRUE)
    if (inherits(out, "om")) {
      return(out)
    }
    cli::cli_warn("`Populate(OM)` failed with error:\n\n{.val {as.character(out)}} \n \nReturning OM object")
    return(OM)
  }
  OM
}

.ProcessSSAllocation <- function(OM, RepList, StockName, FleetNames) {
  ComplexName <- names(OM@Data)
  Allocation <- MakeNamedList(ComplexName)
  AgeClasses <- .GetSSAgeClasses(RepList[[1]])
  YearsList <- .GetSSYears(RepList[[1]], pYear = 1)

  CatchFrac <- RepList[[1]]$catage |>
    .DropXXCols() |>
    dplyr::filter(Yr == max(Yr), Type == 'dead') |>
    tidyr::pivot_longer(as.character(AgeClasses)) |>
    dplyr::group_by(Fleet) |>
    dplyr::summarise(Catch = sum(value), .groups = "drop") |>
    dplyr::mutate(Catch = Catch / sum(Catch)) 
    
    
  nFleet <- length(FleetNames)

  Allocation[[1]] <- array(CatchFrac$Catch,
                      dim = c(1, nFleet),
                      dimnames = list(
                        Sim = 1,
                        Fleet = FleetNames
                      )
  )
  
  OM@Allocation <- Allocation
  OM
}


.GetSSYears <- function(replist, pYear = 30) {
  Seasons <- ifelse(is.null(replist$nseasons), 1, replist$nseasons)
  FirstHistYear <- replist$startyr
  LastHistYear <- replist$endyr
  HistYears <- FirstHistYear:LastHistYear
  nYear <- length(HistYears)

  YearsHist <- CalcYears(nYear, pYear, LastHistYear, Seasons, "Historical")
  YearsProj <- CalcYears(nYear, pYear, LastHistYear, Seasons, "Projection")

  list(
    nYear = nYear,
    pYear = pYear,
    CurrentYear = LastHistYear,
    YearsHist = YearsHist,
    YearsProj = YearsProj,
    TimeUnits = CalcTSUnits(Seasons),
    Seasons = Seasons
  )
}

.ProcessSSStockName <- function(StockName, nStock) {
  if (is.null(StockName)) {
    if (nStock == 1) {
      StockName <- "Combined Sex"
    } else if (nStock == 2) {
      StockName <- c("Female", "Male")
    } else {
      cli::cli_abort("`nStock` should be {.val {1} or {2}}")
    }
  }

  if (length(StockName) != nStock) {
    cli::cli_abort("`StockName` ({.val {StockName}}) should be length `nStock` ({.val {nStock}})")
  }
  StockName
}

.ProcessSSFleetNames <- function(FleetNames, SSFleetNames) {
  nFleet <- length(SSFleetNames)
  if (is.null(FleetNames)) {
    FleetNames <- SSFleetNames
  }

  if (length(FleetNames) != nFleet) {
    cli::cli_abort("`FleetNames` should be length `nFleet`: {.val {nFleet}}")
  }

  FleetNames
}


## --- Stock ----

.SS2Stock <- function(st, RepList, YearsList, nSim,
                     LengthUnits = "cm", WeightUnits = "kg", R0Units = 1) {

  if (!is.null(RepList[[1]]$movement) && nrow(RepList[[1]]$movement) > 0)
    cli::cli_alert_warning("Movement detected in SS model but not imported right now.")

  Stock        <- Stock(Name = ifelse(st == 1, "Female", "Male"))
  Stock@Ages   <- .SS2Ages(st, RepList, YearsList)
  Stock@Length <- .SS2Length(st, RepList, YearsList, Ages = Stock@Ages, Units = LengthUnits) |> ReduceDims()
  Stock@Weight <- .SS2Weight(st, RepList, YearsList, Ages = Stock@Ages, Units = WeightUnits) |> ReduceDims()

  Stock@NaturalMortality <- .SS2NaturalMortality(st,
                                                RepList,
                                                YearsList,
                                                Ages = Stock@Ages)

  Stock@Maturity <- .SS2Maturity(st, RepList, YearsList, Ages = Stock@Ages) |>
    ReduceDims()

  Stock@Fecundity <- .SS2Fecundity(st, RepList, YearsList, Ages = Stock@Ages) |>
    ReduceDims()

  Stock@SRR <- .SS2SRR(st, RepList, YearsList, Ages = Stock@Ages, nSim, R0Units = R0Units)
  Stock@nYear <- YearsList$nYear
  Stock@pYear <- YearsList$pYear
  Stock@Seasons <- YearsList$Seasons
  Stock@nSim <- nSim
  Stock
}

.SS2Ages <- function(st, RepList, YearsList) {
  Ages(
    MaxAge = .CalcSSMaxAgeClass(RepList[[1]], YearsList),
    MinAge = .CalcSSMinAgeClass(RepList[[1]], YearsList),
    Units  = CalcTSUnits(RepList[[1]]$nseasons)
  )
}


.GetSSAgeClasses <- function(replist) {
  AgeClasses <- suppressWarnings(as.numeric(colnames(replist$natage)))
  AgeClasses[!is.na(AgeClasses)]
}

.GetSSLengthClasses <- function(replist) {
  if (!is.na(replist$lbinspop[1]))
    return(replist$lbinspop) # lower bounds
  replist$biology$Len_lo[replist$biology$GP == 1]
}

.CalcSSMaxAgeClass <- function(replist, YearsList) {
  AgeClasses <- .GetSSAgeClasses(replist)
  TimeUnits <- YearsList$TimeUnits
  maxAgeYear <- max(AgeClasses)
  validTimeUnits <- c("year", "half-year", "quarter", "month", "week", "day")
  if (TimeUnits == "year") {
    return(maxAgeYear)
  } else if (TimeUnits == "half-year") {
    return(maxAgeYear + 1 / 2)
  } else if (TimeUnits == "quarter") {
    return((maxAgeYear + 3 / 4) * 4)
  } else if (TimeUnits == "month") {
    return((maxAgeYear + 11 / 12))
  } else if (TimeUnits == "week") {
    return((maxAgeYear + 51 / 52))
  } else if (TimeUnits == "day") {
    return((maxAgeYear + 364 / 365))
  } else {
    cli::cli_abort("`TimeUnits` must be one of: {.val {validTimeUnits}}")
  }
}

.CalcSSMinAgeClass <- function(replist, YearsList) {
  AgeClasses <- .GetSSAgeClasses(replist)
  TimeUnits <- YearsList$TimeUnits
  if (TimeUnits == "year") {
    return(min(AgeClasses))
  }

  birthseas <- .GetSSBirthSeas(replist)
  if (birthseas == 1) {
    return(min(AgeClasses))
  }

  MaxAge <- .CalcSSMaxAgeClass(replist, YearsList)
  Ages   <- seq(min(AgeClasses), by = 1 / YearsList$Seasons, to = MaxAge)
  Ages[birthseas] * YearsList$Seasons
}

.GetSSLengthAtAge <- function(st, replist, YearsList) {
  
  Age_Beg <- Len_Beg <- NULL # CRAN 
  
  YearsHist <- YearsList$YearsHist
  endgrowth <- dplyr::filter(replist$endgrowth, Sex == st)

  endgrowth |>
    dplyr::select(Age = Age_Beg, Value = Len_Beg) |>
    dplyr::mutate(Year = YearsHist[1]) |>
    dplyr::arrange(Age, Year) |>
    dplyr::select(Age, Year, Value) |>
    DF2Array()
}

.GetSSLengthCVAtAge <- function(st, replist, YearsList) {
  
  Age_Beg <- SD_Beg <- NULL # CRAN
  
  YearsHist <- YearsList$YearsHist
  dplyr::filter(replist$endgrowth, Sex == st) |>
    dplyr::select(Age = Age_Beg, SD_Beg, Len_Beg) |>
    dplyr::mutate(Year = YearsHist[1], Value = SD_Beg / Len_Beg) |>
    dplyr::arrange(Age, Year) |>
    dplyr::select(Age, Year, Value) |>
    dplyr::mutate(Value=ifelse(is.finite(Value), Value, 0)) |>
    DF2Array()
}

.SS2Length <- function(st, RepList, YearsList, Ages, Units = "cm") {
  Length <- Length(Pars = list())
  Length@Units <- Units

  Length@MeanAtAge <- purrr::map(RepList, \(replist) {
    .GetSSLengthAtAge(st, replist, YearsList)
  }) |>
    List2Array("Sim", pos = 1) |>
    .ArraySubsetAge(Ages = Ages@Classes) |>
    ReduceDims()

  Length@CVatAge <- purrr::map(RepList, \(replist) {
    .GetSSLengthCVAtAge(st, replist, YearsList)
  }) |>
    List2Array("Sim", pos = 1) |>
    .ArraySubsetAge(Ages = Ages@Classes) |>
    ReduceDims()

  # ASK
  AgeClasses <- Ages@Classes
  Length@Classes <- .GetSSLengthClasses(RepList[[1]])

  ALK <- purrr::map(RepList, \(replist) .GetSSALK(
    st, replist,
    AgeClasses,
    Length@Classes,
    YearsList
  )) |>
    List2Array("Sim", pos = 1) |>
    AddDimension("Year", YearsList$YearsHist[1], 4)
  
  Length@ALK <- ALK

  if (length(AgeClasses) != dim(Length@MeanAtAge)[2]) {
    cli::cli_abort(c(
      "x" = "Number of age-classes for `Length@MeanAtAge` does not match `Ages@Classes`",
      "i" = "`Length@MeanAtAge` has {.val {dim(Length@MeanAtAge)[2]}} age classes",
      "i" = "`Ages@Classes` has {.val {length(Ages@Classes)}} age classes"
    ))
  }
  # TODO - add parameters and models
  # https://nmfs-ost.github.io/ss3-doc/SS330_User_Manual_release.html#Growth
  Length
}

.GetSSLengthWeightPars <- function(st, replist) {
  c(
    Alpha = replist$Growth_Parameters[st, ]$WtLen1,
    Beta = replist$Growth_Parameters[st, ]$WtLen2
  )
}

.GetSSWeightAtLength <- function(st, replist, YearsList, LengthClasses) {
  LWPars     <- .GetSSLengthWeightPars(st, replist)
  MidClasses <- .ClassMidpoints(LengthClasses)
  Value      <- WeightatLength(MidClasses, Alpha = LWPars[["Alpha"]], Beta = LWPars[["Beta"]])
  array(Value, dim = c(length(LengthClasses), 1),
       dimnames = list(Class = LengthClasses, Year = YearsList$YearsHist[1]))
}

.GetSSWeightAtAge <- function(st, replist, YearsList) {
  
  Age_Beg <- NULL
  
  if (!is.null(replist$mean_body_wt)) {
    cli::cli_abort("`replist$mean_body_wt` not currently supported.", .internal = TRUE)
    # TODO - update
    # Wt_age_df <- replist$mean_body_wt[replist$mean_body_wt$Morph == st, ]
    # Wt_age_df <- Wt_age_df[findInterval(mainyrs, Wt_age_df$Yr), ]
    # Wt_age <- do.call(rbind, lapply(0:n_age, function(x) parse(text = paste0("Wt_age_df$`", x, "`")) %>% eval()))
    # if(ncol(Wt_age) == nyears - 1) Wt_age <- cbind(Wt_age, endgrowth$Wt_Beg[-1]
  }
  
  YearsHist <- YearsList$YearsHist
  dplyr::filter(replist$endgrowth, Sex == st) |>
    dplyr::select(Age = Age_Beg, Value = Wt_Beg) |>
    dplyr::mutate(Year = YearsHist[1]) |>
    dplyr::arrange(Age, Year) |>
    dplyr::select(Age, Year, Value) |>
    DF2Array()
}

.SS2Weight <- function(st, RepList, YearsList, Ages, Units = "kg") {
  Weight <- Weight()
  Weight@Units <- Units

  Weight@MeanAtAge <- purrr::map(RepList, \(replist) {
    .GetSSWeightAtAge(st, replist, YearsList)
  }) |>
    List2Array("Sim", pos = 1) |>
    .ArraySubsetAge(Ages = Ages@Classes) |>
    ReduceDims()

  if (Ages@Classes |> length() != dim(Weight@MeanAtAge)[2]) {
    cli::cli_abort(c(
      "x" = "Number of age-classes for `Weight@MeanAtAge` does not match `Ages@Classes`",
      "i" = "`Weight@MeanAtAge` has {.val {dim(Weight@MeanAtAge)[2]}} age classes",
      "i" = "`Ages@Classes` has {.val {length(Ages@Classes)}} age classes"
    ))
  }

  LengthClasses  <- .GetSSLengthClasses(RepList[[1]])
  Weight@Classes <- LengthClasses

  Weight@MeanAtLength <- purrr::map(RepList, \(replist) {
    .GetSSWeightAtLength(st, replist, YearsList, LengthClasses)
  }) |>
    List2Array("Sim", pos = 1) |>
    ReduceDims()

  Weight
}

.FillValues <- function(Value) {
  for (i in seq_along(Value)[-1]) {
    if (is.na(Value[i])) {
      Value[i] <- Value[i - 1]
    }
  }
  Value
}

.ConvertSSMSeasonal <- function(M_at_age, YearsList, Ages) {
  
  AgeAnnual <- NULL # CRAN check hacks
  
  # Convert to seasonal M
  if (YearsList$TimeUnits == "quarter") {
    M_at_ageDF <- Array2DF(M_at_age)
    M_at_ageDF$AgeAnnual <- M_at_ageDF$Age
    
    AgeClassesFull <- seq(0, to = max(Ages@Classes), by = 1 / 4)
    tempDF <- data.frame(
      Age = AgeClassesFull,
      Year = rep(unique(M_at_ageDF$Year), each = length(AgeClassesFull))
    )
    
    M_at_ageDF$Value <- M_at_ageDF$Value / YearsList$Seasons
    M_at_ageDF_seasonal <- dplyr::left_join(tempDF, M_at_ageDF,
                                            by = dplyr::join_by(Age, Year)
    ) |>
      dplyr::select(-AgeAnnual) |>
      dplyr::group_by(Year) |>
      dplyr::mutate(Value = .FillValues(Value)) |>
      dplyr::ungroup()
    return(DF2Array(M_at_ageDF_seasonal))
  } else {
    cli::cli_abort("Currently only 'year' and 'quarter' are supported for `TimeUnits`", .internal = TRUE)
  }
}

.GetSSMAtAge <- function(st, replist, YearsList, Ages) {
  AgeClasses <- .GetSSAgeClasses(replist)
  
  if (!is.null(replist$Natural_Mortality)) {
    
    if (is.null(replist$Natural_Mortality$`Beg/Mid`))
      replist$Natural_Mortality$`Beg/Mid` <- 'B'
    
    if (is.null(replist$Natural_Mortality$Era))
      replist$Natural_Mortality$Era <- 'TIME'
    
    M_at_ageDF <- replist$Natural_Mortality |>
      dplyr::filter(Sex==st, 
                    `Beg/Mid`=='B',
                    Era == 'TIME')
    
    if (is.null(M_at_ageDF$Year)) {
      M_at_ageDF$Year <- M_at_ageDF$Yr
      M_at_ageDF$Yr <- NULL
    }
    
    M_at_age <- M_at_ageDF |>
      dplyr::select(dplyr::all_of(as.character(AgeClasses))) |>
      t()
    
    dimnames(M_at_age) <- list(
      Age = AgeClasses,
      Year = YearsList$YearsHist[seq_len(ncol(M_at_age))]
    )
    
    if (YearsList$TimeUnits == "year") 
      return(M_at_age)
    
    return(
      .ConvertSSMSeasonal(M_at_age, YearsList, Ages)
    )

  }
  
  M_at_ageDF <- replist$M_at_age |> dplyr::filter(Sex == st)
  if (is.null(M_at_ageDF$Year)) {
    M_at_ageDF$Year <- M_at_ageDF$Yr
  }
  Years <- unique(M_at_ageDF$Year)
  
  M_at_age <- M_at_ageDF |>
    dplyr::filter(Sex == st) |>
    dplyr::select(dplyr::all_of(as.character(AgeClasses))) |>
    t()
  
  dimnames(M_at_age) <- list(
    Age = AgeClasses,
    Year = Years
  )

  if (all(is.na(M_at_age[nrow(M_at_age), ]))) {
    endgrowth <- replist$endgrowth |> dplyr::filter(Sex == st)
    M_at_age[nrow(M_at_age), ] <- endgrowth$M[length(AgeClasses)]
  }

  if (YearsList$TimeUnits == "year") {
    return(M_at_age)
  }
  .ConvertSSMSeasonal(M_at_age, YearsList, Ages)
}

.SS2NaturalMortality <- function(st, RepList, YearsList, Ages) {
  NaturalMortality <- NaturalMortality(Pars = list())
  NaturalMortality@MeanAtAge <- purrr::map(RepList, \(replist) {
    .GetSSMAtAge(st, replist, YearsList, Ages)
  }) |>
    List2Array("Sim", pos = 1) |>
    .ArraySubsetAge(Ages = Ages@Classes) |>
    ReduceDims()

  NaturalMortality
}

.GetSSMaturityAtAge <- function(st, replist, YearsList, Ages) {
  Age_Beg <- NULL # CRAN
  endgrowth <- replist$endgrowth |> dplyr::filter(Sex == st)
  seas <- unique(endgrowth$Seas)

  if (length(seas) > 1)
    return(.GetSSMaturityAtAgeSeasonal(st, replist, YearsList, Ages))

  if (any(endgrowth$Age_Mat < 0)) endgrowth$Age_Mat <- abs(endgrowth$Age_Mat) # Should all be 1's
  if (any(endgrowth$Len_Mat < 0)) endgrowth$Len_Mat <- abs(endgrowth$Len_Mat)
  Mat_age <- endgrowth$Len_Mat * endgrowth$Age_Mat
  array(Mat_age,
    dim = c(length(Ages@Classes), 1),
    dimnames = list(
      Age = Ages@Classes,
      Year = YearsList$YearsHist[1]
    )
  )
}

# For seasonal models, `endgrowth` has one row per (Sex, Morph, Seas,
# Age_Beg) with Age_Beg the *annual* age -- multiple seasonal rows share the
# same annual age. Map each quarterly Age class in `Ages@Classes` back to
# its underlying annual Age_Mat/Len_Mat value via the birth-season offset,
# mirroring .GetSSFecunditySeasonal() (maturity x fecundity is the same
# underlying per-age quantity, just without the fecundity term).
.GetSSMaturityAtAgeSeasonal <- function(st, replist, YearsList, Ages) {
  Age_Beg <- NULL # CRAN

  mat_age <- replist$endgrowth |>
    dplyr::filter(Sex == st) |>
    dplyr::distinct(Age_Beg, .keep_all = TRUE) |>
    dplyr::arrange(Age_Beg)

  q_ages <- Ages@Classes
  n_ages <- length(q_ages)

  if (nrow(mat_age) == 0L) {
    return(array(0, dim = c(n_ages, 1L),
                 dimnames = list(Age = q_ages, Year = YearsList$YearsHist[1])))
  }

  if (any(mat_age$Age_Mat < 0)) mat_age$Age_Mat <- abs(mat_age$Age_Mat) # Should all be 1's
  if (any(mat_age$Len_Mat < 0)) mat_age$Len_Mat <- abs(mat_age$Len_Mat)
  mat_age$Maturity <- mat_age$Len_Mat * mat_age$Age_Mat

  birthseas <- .GetSSBirthSeas(replist)
  n_seasons <- length(unique(replist$endgrowth$Seas[replist$endgrowth$Sex == st]))

  n_idx <- seq_len(n_ages) - 1L
  seasons_to_yr_bound <- n_seasons - birthseas + 1L

  age_beg <- ifelse(
    n_idx < seasons_to_yr_bound,
    0L,
    as.integer(floor((n_idx - seasons_to_yr_bound) / n_seasons) + 1L)
  )

  max_age  <- max(mat_age$Age_Beg)
  mat_vals <- mat_age$Maturity[match(pmin(age_beg, max_age), mat_age$Age_Beg)]

  array(mat_vals,
    dim = c(n_ages, 1L),
    dimnames = list(Age = q_ages, Year = YearsList$YearsHist[1])
  )
}

.SS2Maturity <- function(st, RepList, YearsList, Ages) {
  Maturity <- Maturity(Pars = list())
  Maturity@MeanAtAge <- purrr::map(RepList, \(replist) {
    .GetSSMaturityAtAge(st, replist, YearsList, Ages)
  }) |>
    List2Array("Sim", pos = 1) |>
    .ArraySubsetAge(Ages = Ages@Classes)
  Maturity
}

.GetSSFecundity <- function(st, replist, YearsList, Ages) {
  
  Age_Beg <- `Mat*Fecund` <- `Mat_F_wtatage` <- NULL
  endgrowth <- replist$endgrowth |> dplyr::filter(Sex == st)
  seas <- unique(endgrowth$Seas)

  if (length(seas) > 1) {
    return(
      .GetSSFecunditySeasonal(st, replist, YearsList, Ages)
    )
  }

  if (!is.null(replist$endgrowth[["Mat*Fecund"]])) {
    fec_age <- replist$endgrowth |>
      dplyr::filter(Morph == 1, Sex == st) |>
      dplyr::select(Age = Age_Beg, Fecundity = `Mat*Fecund`)
  } else {
    if (!is.null(replist$endgrowth$Mat_F_wtatage)) {
      fec_age <- replist$endgrowth |>
        dplyr::filter(Morph == 1, Sex == st) |>
        dplyr::select(Age_Beg, Fecundity = Mat_F_wtatage)
    }
  }

  array(fec_age$Fecundity,
    dim = c(length(Ages@Classes), 1),
    dimnames = list(
      Age = Ages@Classes,
      Year = YearsList$YearsHist[1]
    )
  )
}

.GetSSFecunditySeasonal <- function(st, replist, YearsList, Ages) {

  Age_Beg <- `Mat*Fecund` <- `Mat_F_wtatage` <- NULL

  if (!is.null(replist$endgrowth[["Mat*Fecund"]])) {
    fec_age <- replist$endgrowth |>
      dplyr::filter(Morph == 1, Sex == st) |>
      dplyr::select(Age = Age_Beg, Fecundity = `Mat*Fecund`) |>
      dplyr::distinct(Age, .keep_all = TRUE)
  } else {
    if (!is.null(replist$endgrowth$Mat_F_wtatage)) {
      fec_age <- replist$endgrowth |>
        dplyr::filter(Morph == 1, Sex == st) |>
        dplyr::select(Age = Age_Beg, Fecundity = Mat_F_wtatage) |>
        dplyr::distinct(Age, .keep_all = TRUE)
    }
  }

  q_ages <- Ages@Classes
  n_ages <- length(q_ages)

  # For Sex > 1, Morph == 1 rows may not exist; return zeros (e.g. males)
  if (!exists("fec_age") || nrow(fec_age) == 0L) {
    return(array(0, dim = c(n_ages, 1L),
                 dimnames = list(Age = q_ages, Year = YearsList$YearsHist[1])))
  }

  birthseas <- .GetSSBirthSeas(replist)
  n_seasons <- length(unique(replist$endgrowth$Seas[replist$endgrowth$Sex == st]))

  n_idx <- seq_len(n_ages) - 1L
  seasons_to_yr_bound <- n_seasons - birthseas + 1L

  age_beg <- ifelse(
    n_idx < seasons_to_yr_bound,
    0L,
    as.integer(floor((n_idx - seasons_to_yr_bound) / n_seasons) + 1L)
  )

  max_age  <- max(fec_age$Age)
  fec_vals <- fec_age$Fecundity[match(pmin(age_beg, max_age), fec_age$Age)]

  array(fec_vals,
    dim = c(n_ages, 1L),
    dimnames = list(Age = q_ages, Year = YearsList$YearsHist[1])
  )
}

.SS2Fecundity <- function(st, RepList, YearsList, Ages) {
  # TODO import model and parameters from SS output
  # replist$FecPar1
  # replist$FecPar1name
  # replist$FecPar2
  # replist$FecType
  # replist$Fecundity_option
  # can do the same with maturity

  Fecundity <- Fecundity(Pars = list())
  Fecundity@MeanAtAge <- purrr::map(RepList, \(replist) {
    .GetSSFecundity(st, replist, YearsList, Ages)
  }) |>
    List2Array("Sim", pos = 1) |>
    .ArraySubsetAge(Ages = Ages@Classes)
  Fecundity
}

.SS2Depletion <- function(st, RepList, YearsList) {
  Depletion <- Depletion(Reference = "SB0")

  SB0 <- purrr::map(RepList, \(replist) {
    replist$timeseries |>
      dplyr::filter(Era == "VIRG") |>
      getElement("SpawnBio") |>
      sum(na.rm = TRUE)
  }) |> unlist()

  SB1 <- purrr::map(RepList, \(replist) {
    replist$timeseries |>
      dplyr::filter(Yr == YearsList$YearsHist[1]) |>
      getElement("SpawnBio") |>
      sum(na.rm = TRUE)
  }) |> unlist()

  if (!all(round(SB1 / SB0, 2) == 1)) {
    Depletion@Initial <- SB1 / SB0
  }

  # Don't populate Depletion Final or else it will optimize for q
  # if (st==1) {
  #   SBCurr <- purrr::map(RepList, \(replist) {
  #     replist$timeseries |>
  #       dplyr::filter(Yr == max(mainyrs)) |>
  #       getElement("SpawnBio") |>
  #       sum(na.rm = TRUE)
  #   }) |> unlist()
  #
  #   Depletion@Final <- SBCurr/SB0
  # }

  Depletion
}

.GetSSSRRPars <- function(replist) {
  mainyrs <- NULL  # CRAN
  # SRR Model and Parameters
  if (replist$SRRtype == 3 || replist$SRRtype == 6) { # Beverton-Holt SR
    par <- replist$parameters[grepl("steep", rownames(replist$parameters)), ]
    h_out <- par$Value
    h_out[h_out < 0.2] <- 0.2
    h_out[h_out > 0.999] <- 0.999
    return(list(h = h_out))
  } else if (replist$SRRtype == 2) {
    par <- replist$parameters[grepl("SR_Ricker", rownames(replist$parameters)), ]
    h_out <- par$Value
    h_out[h_out < 0.2] <- 0.2
    return(list(hR = h_out))
  } else if (replist$SRRtype == 7) {
    cli::cli_abort(
      "SS3 `SRRtype == 7` currently not supported" ,.internal = TRUE
    )
    
    s_frac <- replist$parameters$Value[replist$parameters$Label == "SR_surv_Sfrac"]
    Beta <- replist$parameters$Value[replist$parameters$Label == "SR_surv_Beta"]
    s0 <- 1 / SpR0
    z0 <- -log(s0)
    z_min <- z0 * (1 - s_frac)
    h_out <- 0.2 * exp(z0 * s_frac * (1 - 0.2^Beta))
    h_out[h_out < 0.2] <- 0.2
    h_out[h_out > 0.999] <- 0.999
    return(list(h = h_out))
  } else {
    mainyrs <- replist$startyr:replist$endyr
    if (length(replist$SRRtype) && nchar(replist$SRRtype)<=1) {
      cli::cli_alert_warning(
        "`replist$SRRtype` is empty. Assuming {.val Beverton-Holt SRR}"
      )
    } else {
      cli::cli_alert_warning(
      "`replist$SRRtype` ({replist$SRRtype}) is not supported. Assuming {.val Beverton-Holt SRR}"
      )
    }
    
    if (packageVersion("r4ss") == "1.24") {
      SR_ind <- match(mainyrs, replist$recruit$year)
      SSB <- replist$recruit$spawn_bio[SR_ind]
      SSB0 <- replist$derived_quants[replist$derived_quants$LABEL == "SPB_Virgin", 2]
    } else {
      SR_ind <- match(mainyrs, replist$recruit$Yr)
      SSB <- replist$recruit$SpawnBio[SR_ind]
      SSB0 <- replist$derived_quants[replist$derived_quants$Label == "SSB_Virgin", 2]
    }
    R0 <- exp(replist$parameters$Value[replist$parameters$Label == "SR_LN(R0)"])
    rec <- replist$recruit$pred_recr[SR_ind] # recruits to age 0
    
    SpR0 <- SSB0 / (R0) #  * ifelse(season_as_years, nseas, 1))
    SRrel <- 1
    h_out <- SRopt(1, SSB, rec, SpR0, plot = FALSE, type = ifelse(SRrel == 1, "BH", "Ricker"))
    h_out[h_out < 0.2] <- 0.2
    h_out[h_out > 0.999] <- 0.999
    return(list(h = h_out))
  }
}

.GetSSRecDevsEarly <- function(replist, YearsList, Ages, st) {
  
  N1 <- N0 <- Deviation <- NULL # CRAN
  
  SSAgeClasses <- .GetSSAgeClasses(replist)
  YearsHist <- YearsList$YearsHist
  Virg <- replist$natage |>
    dplyr::filter(Era == "VIRG", `Beg/Mid` == "B", Seas == 1, Sex == st) |>
    dplyr::select(as.character(SSAgeClasses), Sex) |>
    tidyr::pivot_longer(as.character(SSAgeClasses),
      names_to = "Age", values_to = "N0"
    )

  Init <- replist$natage |>
    dplyr::filter(Yr == min(YearsHist), `Beg/Mid` == "B", Seas == 1, Sex == st) |>
    dplyr::select(as.character(SSAgeClasses), Sex) |>
    tidyr::pivot_longer(as.character(SSAgeClasses),
      names_to = "Age", values_to = "N1"
    )

  Deviations <- dplyr::left_join(Virg, Init, by = dplyr::join_by(Sex, Age)) |>
    dplyr::mutate(Deviation = N1 / N0) |>
    dplyr::mutate(
      Value = ifelse(is.finite(Deviation), Deviation, 1),
      Age = as.numeric(Age)
    ) |>
    dplyr::select(Age, Value) |>
    dplyr::arrange(Age)

  FullAgeClasses <- seq(0, by = 1 / CalcSeasons(Ages@Units), to = max(Ages@Classes))

  dev <- array(rep(Deviations$Value, each = replist$nseasons),
    dim = length(FullAgeClasses),
    dimnames = list(Age = FullAgeClasses)
  ) |>
    .ArraySubsetAge(Ages@Classes[-1])

  dev
}


.GetSSRecDevs <- function(replist, YearsList, Ages) {
  YearsHist <- YearsList$YearsHist
  Seasons   <- YearsList$Seasons
  recruit   <- replist$recruit

  Rec_main <- recruit[recruit$Yr %in% YearsHist, ]

  dev <- Rec_main$pred_recr / Rec_main$exp_recr
  dev <- array(dev,
    dim = length(dev),
    dimnames = list(Year = YearsHist[match(Rec_main$Yr, YearsHist)])
  )

  lag <- round(min(Ages@Classes) * Seasons)
  if (lag > 0) {
    # R0_virgin: total recruitment across all sexes at virgin unfished state.
    # Sum over sexes (Sex dimension) to match pred_recr which is sex-combined.
    AgeClasses <- .GetSSAgeClasses(replist)
    birthseas  <- .GetSSBirthSeas(replist)
    R0_virgin  <- dplyr::filter(
        replist$natage,
        `Beg/Mid` == "B",
        Era == "VIRG",
        Seas == birthseas
      ) |>
      tidyr::pivot_longer(as.character(AgeClasses),
        names_to  = "Age",
        values_to = "Number"
      ) |>
      dplyr::mutate(Age = as.numeric(Age)) |>
      dplyr::filter(Age == min(Age)) |>
      dplyr::summarise(Number = sum(Number)) |>
      dplyr::pull(Number)

    if (length(R0_virgin) > 0 && is.finite(R0_virgin[1]) && R0_virgin[1] > 0) {
      dev[1] <- Rec_main$pred_recr[1] / R0_virgin[1]
    }
  }

  if (Seasons == 1)
    return(dev)

  # expand for seasons
  dev <- rep(dev, each = Seasons)
  array(dev,
    dim = length(dev),
    dimnames = list(Year = YearsHist)
  )
}

.GetSSBirthSeas <- function(replist) {
  # birthseas can be a vector (e.g. c(2,3) for NPSWO) but represents a single
  # shared spawning event; using the last (latest) season as the birth season.
  if (is.null(replist$birthseas)) return(1L)
  max(replist$birthseas)
}

.GetSSR0 <- function(st, replist, YearsList) {
  
  Number <- NULL # cran checks
  
  AgeClasses <- .GetSSAgeClasses(replist)
  birthseas <- .GetSSBirthSeas(replist)

  R0 <- dplyr::filter(
    replist$natage, Sex == st,
    `Beg/Mid` == "B",
    Era == "VIRG",
    Seas == birthseas
  ) |>
    tidyr::pivot_longer(as.character(AgeClasses),
      names_to = "Age",
      values_to = "Number"
    ) |>
    dplyr::mutate(Age = as.numeric(Age)) |>
    dplyr::filter(Age == min(Age)) |>
    dplyr::pull(Number)

  nSeas <- replist$natage$Seas |>
    unique() |>
    length()
  if (length(R0) != nSeas) {
    R0Vec <- rep(0, nSeas)
    R0Vec[birthseas] <- R0
    R0 <- R0Vec
  }


  YearsAll <- c(YearsList$YearsHist, YearsList$YearsProj)
  R0 <- rep(R0, length(YearsAll))
  R0 <- R0[seq_along(YearsAll)]

  array(R0, length(R0), dimnames = list(Year = YearsAll))
}

.SS2SRR <- function(st, RepList, YearsList, Ages, nSim, R0Units = 1) {
  SD <- purrr::map(RepList, \(replist) replist$sigma_R_in) |>
    unlist() |>
    as.numeric()
  R0 <- purrr::map(RepList, \(replist) .GetSSR0(st, replist, YearsList)) |>
    List2Array("Sim", pos = 1)

  Seasons <- YearsList$Seasons
  SpawnTimeFrac <- ifelse(is.na(RepList[[1]]$Spawn_timing_in_season), 0,
                          RepList[[1]]$Spawn_timing_in_season)

  # Compute SpawnLag: timesteps between SSB evaluation (spawn_month) and
  # first appearance of recruits (birthseas). When these differ, the lag
  # implied by min(Ages@Classes) is wrong and must be overridden.
  spawn_lag <- NULL
  if (Seasons > 1 && !is.null(RepList[[1]]$Spawn_month)) {
    spawn_season <- ceiling(RepList[[1]]$Spawn_month / (12 / Seasons))
    birthseas    <- .GetSSBirthSeas(RepList[[1]])
    computed_lag <- (birthseas - spawn_season) %% Seasons
    # Default lag derived from min(Ages@Classes): Ages@MinAge / Seasons * Seasons = Ages@MinAge
    # which(seq(0,by=1/Seasons,to=MaxAge) == min(Classes)) - 1 == birthseas - 1
    default_lag  <- birthseas - 1L
    if (computed_lag != default_lag)
      spawn_lag <- computed_lag
  }

  SRR <- SRR(SD = SD, R0 = R0, SpawnTimeFrac = SpawnTimeFrac, SpawnLag = spawn_lag, Units = R0Units)

  Pars <- purrr::map(RepList, \(replist) .GetSSSRRPars(replist))
  Pars <- do.call("rbind", Pars)
  ParsList <- list(as.numeric(Pars))
  names(ParsList) <- colnames(Pars)
  SRR@Pars <- ParsList

  SRR@RecDevInit <- purrr::map(RepList, \(replist)
  .GetSSRecDevsEarly(replist, YearsList, Ages, st)) |>
    List2Array("Sim", pos = 1)

  SRR@RecDevHist <- purrr::map(RepList, \(replist)
  .GetSSRecDevs(replist, YearsList, Ages)) |>
    List2Array("Sim", pos = 1)

  AC <- log(SRR@RecDevHist) |>
    apply(1, acf, lag.max = 1, plot = FALSE, na.rm = TRUE) |>
    lapply(getElement, "acf") |>
    lapply(getElement, 2) |>
    unlist()

  AC[!is.finite(AC)] <- 0
  SRR@AC <- AC

  if (st == 2) {
    SRR@SPFrom <- 1
  }

  RecDevs <- GenRecDevs(
    SD = SRR@SD,
    AC = SRR@AC,
    Ages = Ages,
    HistYears  = YearsList$YearsHist,
    ProjYears  = YearsList$YearsProj,
    nSim = nSim,
    RecDevInit = SRR@RecDevInit,
    RecDevHist = SRR@RecDevHist
  )

  SRR@RecDevProj <- RecDevs$RecDevProj
  ProjectionYears <- YearsList$YearsProj
  dimnames(SRR@RecDevProj) <- list(
    Sim = 1:nSim,
    Year = ProjectionYears
  )
  SRR
}


## Fleet ----

.SS2Fleet <- function(st, fl, RepList, YearsList, FleetNames, Stock) {
  AgeClasses                    <- Stock@Ages@Classes
  Fleet                         <- Fleet(FleetNames[fl])
  Fleet@Effort@Effort           <- .SS2Effort(st, fl, RepList, YearsList)
  Fleet@Catchability@Efficiency <- .SS2Catchability(st, fl, RepList, YearsList)
  Fleet@Selectivity             <- .SS2Selectivity(st, fl, RepList,
                                                  YearsList, Stock)
  Fleet@DiscardMortality        <- .SS2DiscardMortality(st, fl, RepList, YearsList,
                                                       Selectivity = Fleet@Selectivity,
                                                       Stock)
  Fleet@Retention               <- .SS2Retention(st, fl, RepList, YearsList,
                                                Selectivity = Fleet@Selectivity,
                                                Stock)

  Fleet@WeightFleetSelected <- .CalcFleetWeightAtAge(
    Selectivity = Fleet@Selectivity,
    Weight      = Stock@Weight,
    Length      = Stock@Length
  )
  Fleet@WeightFleetRetained <- .CalcFleetWeightAtAge(
    Selectivity = Fleet@Selectivity,
    Weight      = Stock@Weight,
    Length      = Stock@Length,
    Retention   = Fleet@Retention
  )
  Fleet
}


.GetSSApicalF <- function(st, fl, replist, YearsList) {
  AgeClasses <- .GetSSAgeClasses(replist)
  
  FInteract <- replist$fatage |>
    dplyr::filter(Sex == st, Fleet == fl, Yr %in% YearsList$YearsHist)
  
  nMorph <- FInteract$Morph |>
    unique() |>
    length()
  
  if (nMorph > 1) 
    cli::cli_abort("More than 1 Morph not currently supported", .internal = TRUE)
  
  FInteract <- t(FInteract[, as.character(AgeClasses)])
  dimnames(FInteract) <- list(
    Age = AgeClasses,
    Year = YearsList$YearsHist
  )
  
  FInteractApical <- apply(FInteract, c("Year"), max) * 1 / replist$nseasons
  FInteractApical
}


.GetSSEffort <- function(st, fl, replist, YearsList, type = c("Effort", "q")) {
  type <- match.arg(type)

  # Fishing Effort is proportional to FInteract - ie the fishing mortality on
  # all fish that interact with the gear, including those that are discarded alive
  # ie don't suffer discard mortality
  FInteractApical <- .GetSSApicalF(st, fl, replist, YearsList)

  FInteractApicalTerminal <- FInteractApical
  FInteractApicalTerminal[] <- 0
  
  if (max(FInteractApical) == 0) {
    if (type == "q") 
      return(0)
    
    return(
      array(rep(0, length(YearsList$YearsHist)), 
            dimnames = list(Year=YearsList$YearsHist))
    )
  }

  ind <- which(FInteractApical > 0) |> max()
  FInteractApicalTerminal[] <- FInteractApical[ind]
  if (type == "q") 
    return(FInteractApical[ind])
  
  RelEffort <- FInteractApical / FInteractApicalTerminal
  RelEffort <- array(RelEffort, dim = c(length(RelEffort)))
  dimnames(RelEffort) <- list(Year = YearsList$YearsHist)

  RelEffort
}

.SS2Effort <- function(st, fl, RepList, YearsList) {
  purrr::map(RepList, \(replist)
             .GetSSEffort(st, fl, replist, YearsList)) |>
    List2Array("Sim", pos = 1)
}

.SS2Catchability <- function(st, fl, RepList, YearsList) {
  q <- purrr::map(RepList, \(replist)
                  .GetSSEffort(st, fl, replist, YearsList, type = "q")) |>
    List2Array("Sim", pos = 1, dim1 = "Year") |>
    .Aperm(c("Sim", "Year"))

  dimnames(q)$Year <- YearsList$YearsHist[1]
  q
}

.GetSSDiscardMortalityAtLength <- function(st, fl, replist, YearsList, Stock) {
  DiscardAtLength <- replist$sizeselex[replist$sizeselex$Fleet == fl &
    replist$sizeselex$Sex == st &
    replist$sizeselex$Factor == "Mort", ] |>
    dplyr::filter(Yr %in% YearsList$YearsHist)
  DiscardYears <- DiscardAtLength$Yr

  MidClasses <- suppressWarnings(as.numeric(colnames(DiscardAtLength)))
  MidClasses <- MidClasses[!is.na(MidClasses)]

  DiscardAtLength <- DiscardAtLength[, as.character(MidClasses)]
  DiscardAtLength <- t(DiscardAtLength)

  dimnames(DiscardAtLength) <- list(
    Class = .GetSSLengthClasses(replist),
    Year = DiscardYears
  )
  DiscardAtLength
}

# Detects SS3 discard_option = 3 ("all discarded fish die"), which overrides
# any length-based discard mortality curve from sizeselex's "Mort" factor.
.IsSSDiscardAllDead <- function(st, fl, replist, tol = 0.01) {
  ageselex <- replist$ageselex
  if (is.null(ageselex)) return(FALSE)

  yrs <- sort(unique(
    ageselex$Yr[ageselex$Fleet == fl & ageselex$Sex == st & ageselex$Factor == "dead_nums"]
  ))
  if (length(yrs) == 0) return(FALSE)
  yr <- yrs[length(yrs)]

  AgeCols <- names(ageselex)[suppressWarnings(!is.na(as.numeric(names(ageselex))))]

  GetFactorRow <- function(Factor) {
    row <- ageselex[ageselex$Fleet == fl & ageselex$Sex == st &
      ageselex$Factor == Factor & ageselex$Yr == yr, ]
    if (nrow(row) == 0) return(NULL)
    as.numeric(row[1, AgeCols])
  }

  Sel  <- GetFactorRow("sel_nums")
  Ret  <- GetFactorRow("sel*ret_nums")
  Dead <- GetFactorRow("dead_nums")
  if (is.null(Sel) || is.null(Ret) || is.null(Dead)) return(FALSE)

  DiscTotal <- Sel - Ret
  DiscDead  <- Dead - Ret
  valid     <- DiscTotal > 1e-6
  if (!any(valid)) return(FALSE)

  all(abs(DiscDead[valid] / DiscTotal[valid] - 1) < tol)
}


.GetSSALKAnnual <- function(st, replist, AgeClasses, LengthClasses, YearsList) {
  ALK_dim_match <- any(paste0("Seas: 1 Sub_Seas: 2 Morph: ", st) %in% dimnames(replist$ALK)[[3]])
  if (ALK_dim_match) {
    ALK <- replist$ALK[, , paste0("Seas: 1 Sub_Seas: 2 Morph: ", st)]
  } else {
    ALK <- replist$ALK[, , paste0("Seas: 1 Morph: ", (st - 1) * replist$nseasons + 1)]
  }
  if (all(!is.na(replist$lbinspop))) {
    ALK <- ALK[match(replist$lbinspop, dimnames(ALK)$Length), match(AgeClasses, dimnames(ALK)$TrueAge)]
  } else {
    lbinspop <- sort(as.numeric(dimnames(ALK)$Length))
    ALK <- ALK[match(lbinspop, dimnames(ALK)$Length), match(AgeClasses, dimnames(ALK)$TrueAge)]
  }
  ALK <- t(ALK)

  dimnames(ALK) <- list(
    Age = AgeClasses,
    Class = LengthClasses
  )

  maxALK <- apply(ALK, 1, sum)
  maxALK <- matrix(maxALK, nrow(ALK), ncol(ALK))
  ALK <- ALK / maxALK
  ALK
}

.GetSSALKSeasonal <- function(st, replist, AgeClasses, LengthClasses, YearsList) {
  nseasons <- replist$nseasons
  AgeClassesFull <- seq(0, to = max(AgeClasses), by = 1 / YearsList$Seasons)

  ALK_Out <- array(NA,
    dim = c(
      length(AgeClassesFull),
      length(LengthClasses)
    ),
    dimnames = list(
      Age = AgeClassesFull,
      Class = LengthClasses
    )
  )
  for (seas in 1:nseasons) {
    ALK <- replist$ALK[, , paste0("Seas: ", seas, " Sub_Seas: 2 Morph: ", st)]
    lbinspop <- sort(as.numeric(dimnames(ALK)$Length))
    ALK <- ALK[match(lbinspop, dimnames(ALK)$Length), ] |> t()
    names(dimnames(ALK))[1] <- "Age"

    ages <- AgeClassesFull[seq(from = seas, by = YearsList$Seasons, length.out = nrow(ALK))]
    dimnames(ALK)$Age <- ages

    rowind <- match(ages, AgeClassesFull)
    ALK_Out[rowind, ] <- ALK
  }
  .ArraySubsetAge(ALK_Out, AgeClasses)
}


.GetSSALK <- function(st, replist, AgeClasses, LengthClasses, YearsList) {
  if (YearsList$Seasons == 1) {
    return(.GetSSALKAnnual(st, replist, AgeClasses, LengthClasses, YearsList))
  }

  .GetSSALKSeasonal(st, replist, AgeClasses, LengthClasses, YearsList)
}


.SS2DiscardMortality <- function(st, fl, RepList, YearsList, Selectivity, Stock) {
  DiscardMortality <- DiscardMortality()

  DiscardMortality@MeanAtLength <- purrr::map(RepList, \(replist)
  .GetSSDiscardMortalityAtLength(st, fl, replist, YearsList, Stock)) |>
    List2Array("Sim", pos = 1) |>
    ReduceDims()

  AgeClasses <- Stock@Ages@Classes
  LengthClasses <- dimnames(DiscardMortality@MeanAtLength)$Class |> as.numeric()
  DiscardMortality@Classes <- LengthClasses

  Stock@Length <- PopulateLength(
    Length = Stock@Length,
    Ages = Stock@Ages,
    Years = c(YearsList$YearsHist, YearsList$YearsProj),
    nSim = Stock@nSim
  )

  DiscardMortality <- .MeanAtLength2MeanAtAge(
    object = DiscardMortality,
    Length = Stock@Length,
  )

  DiscardMortality@MeanAtAge <- ReduceDims(DiscardMortality@MeanAtAge)

  # Override with 100% discard mortality where SS3's own realized
  # accounting shows discard_option = 3 for this fleet (see
  # .IsSSDiscardAllDead()) 
  if (all(purrr::map_lgl(RepList, \(replist) .IsSSDiscardAllDead(st, fl, replist))))
    DiscardMortality@MeanAtAge[] <- 1

  DiscardMortality
}

.GetSSSelectivityAtAge <- function(st, fl, replist, YearsList, Stock) {
  
  Factor <- NULL # CRAN checks
  
  AgeClasses   <- Stock@Ages@Classes
  SSAgeClasses <- as.character(.GetSSAgeClasses(replist))
  YearsHist    <- YearsList$YearsHist
  nSeas        <- YearsList$Seasons
  YearsAll     <- c(YearsList$YearsHist, YearsList$YearsProj)
  
  year_to_ind <- setNames(seq_along(YearsAll), as.character(YearsAll))
  
  AgeSel_df <- replist$ageselex |>
    dplyr::filter(
      Fleet == fl,
      Sex %in% st,
      Factor == "Asel2",
      Yr %in% YearsHist
    )
  
  #  Non-seasonal
  if (replist$nseasons == 1) {
    AgeSelect <- AgeSel_df |>
      dplyr::select(dplyr::all_of(SSAgeClasses)) |>
      as.matrix() |>
      t()
    
    dimnames(AgeSelect) <- list(Age = AgeClasses, Year = YearsHist)
    col_max <- apply(AgeSelect, 2, max)
    return(sweep(AgeSelect, 2, col_max, "/"))
  }
  
  # Seasonal 
  nAge <- length(AgeClasses)
  
  age_vals     <- as.numeric(SSAgeClasses)
  SeasonalAges <- seq(min(age_vals), max(age_vals) + (nSeas - 1) / nSeas, by = 1 / nSeas)
  
  age_ind <- match(SeasonalAges, AgeClasses, nomatch = 0L)
  valid   <- age_ind > 0L
  age_ind <- age_ind[valid]
  
  MeanAtAge <- matrix(
    NA_real_,
    nrow     = nAge,
    ncol     = length(YearsHist),
    dimnames = list(Age = AgeClasses, Year = YearsHist)
  )
  
  AgeSel_long <- AgeSel_df |>
    dplyr::select(Yr, Seas, dplyr::all_of(SSAgeClasses)) |>
    tidyr::pivot_longer(
      cols      = dplyr::all_of(SSAgeClasses),
      names_to  = "Age",
      values_to = "V"
    ) |>
    dplyr::mutate(Age = as.numeric(Age)) |>
    dplyr::arrange(Yr, Age, Seas)  
  
  AgeSel_split <- split(AgeSel_long, AgeSel_long$Yr)
  
  for (yr in names(AgeSel_split)) {
    vals <- AgeSel_split[[yr]]$V[valid]
    ind1 <- year_to_ind[[yr]]
    ind2 <- year_to_ind[[as.character(as.integer(yr) + 1L)]] - 1L
    MeanAtAge[age_ind, ind1:ind2] <- vals
  }
  
  col_max <- apply(MeanAtAge, 2, max)
  sweep(MeanAtAge, 2, col_max, "/")
}

.GetSSSelectivityAtLength <- function(st, fl, replist, YearsList, Stock) {
  YearsHist <- YearsList$YearsHist

  Sel_df <- replist$sizeselex[replist$sizeselex$Fleet == fl &
    replist$sizeselex$Sex == st &
    replist$sizeselex$Factor == "Lsel" &
    replist$sizeselex$Yr %in% YearsHist, ]

  SelectYears <- Sel_df$Yr

  MidClasses <- suppressWarnings(as.numeric(colnames(Sel_df)))
  MidClasses <- MidClasses[!is.na(MidClasses)]

  SelectAtLength <- as.matrix(Sel_df[, as.character(MidClasses)])
  SelectAtLength <- t(SelectAtLength)

  dimnames(SelectAtLength) <- list(
    Class = .GetSSLengthClasses(replist),
    Year  = SelectYears
  )

  sweep(SelectAtLength, 2, apply(SelectAtLength, 2, max), "/")
}

.SS2Selectivity <- function(st, fl, RepList, YearsList, Stock) {
  # TODO
  # - ideally import SS3 selectivity models and parameters

  Selectivity <- Selectivity(Pars = list())
  Selectivity@MeanAtLength <- purrr::map(RepList, \(replist)
  .GetSSSelectivityAtLength(
    st, fl, replist,
    YearsList, Stock
  )) |>
    List2Array("Sim", pos = 1) 
  Selectivity@Classes <- as.numeric(dimnames(Selectivity@MeanAtLength)$Class)

  Selectivity@MeanAtAge <- purrr::map(RepList, \(replist)
  .GetSSSelectivityAtAge(
    st, fl, replist,
    YearsList, Stock
  )) |>
    List2Array("Sim", pos = 1) 

  Selectivity
}




.GetSSRetentionAtLength <- function(st, fl, replist, YearsList) {
  RetainAtLength <- replist$sizeselex[
    replist$sizeselex$Fleet    == fl &
      replist$sizeselex$Sex    == st &
      replist$sizeselex$Factor == "Ret", ] |>
    dplyr::filter(Yr %in% YearsList$YearsHist)

  RetainYears <- RetainAtLength$Yr

  MidClasses <- suppressWarnings(as.numeric(colnames(RetainAtLength)))
  MidClasses <- MidClasses[!is.na(MidClasses)]

  RetainAtLength <- RetainAtLength[, as.character(MidClasses)] |> t()
  dimnames(RetainAtLength) <- list(
    Class = .GetSSLengthClasses(replist),
    Year  = RetainYears
  )
  RetainAtLength
}

.SS2Retention <- function(st, fl, RepList, YearsList, Selectivity, Stock) {
  Retention                    <- Retention(Pars = list())
  Retention@MeanAtLength       <- purrr::map(RepList, \(replist)
                                             .GetSSRetentionAtLength(st, fl, replist,
                                                                     YearsList)) |>
    List2Array("Sim", pos = 1) |> ReduceDims()

  Retention@MeanAtLength[!is.finite(Retention@MeanAtLength)] <- 0
  Retention@Classes <- as.numeric( dimnames(Retention@MeanAtLength)$Class)

  Retention <- .WeightedAtSize2AtAge(Retention, Selectivity, Stock@Length)

  Retention
}


.ProcessSurveyObsSelectivity <- function(OM, RepList) {
  # Add Selectivity to Obs for Survey indices
  IndexInd <- which(grepl("Obs", OM@Data[[1]]@Survey@Selectivity))

  if (!length(IndexInd)) {
    return(OM)
  }

  Survey_Ind <- which(!RepList[[1]]$IsFishFleet)
  nStock <- nStock(OM)
  YearsList <- .GetSSYears(RepList[[1]], pYear = 1)

  for (fl in Survey_Ind) {
    OM@Obs[[1]][[fl]]@Survey@Selectivity <- MakeNamedList(StockNames(OM))
    for (st in 1:nStock) {
      SurveySelect <- .SS2Selectivity(st, fl, RepList, YearsList, Stock = OM@Stock[[st]])
      OM@Obs[[1]][[fl]]@Survey@Selectivity[[st]] <- SurveySelect@MeanAtAge
    }
  }
  OM
}


# ---- Other Useful Stuff ----

.DropXXCols <- function(array) {
  ind <- which(names(array) != "XX")
  array[, ind]
}


.GetSSNatAge <- function(replist, OM, yrs = NULL, sex = 1) {
  Yr <- Time <- Seas <- NULL # CRAN
  
  if (is.null(yrs)) {
    yrs <- replist$natage |>
      dplyr::filter(Era == "TIME") |>
      dplyr::distinct(Yr) |>
      dplyr::pull(Yr)
  }

  AgeClasses <- OM@Stock[[1]]@Ages@Classes
  AgeClassesFull <- seq(0, to = max(AgeClasses), by = 1 / OM@Seasons)
  HistYears <- Years(OM, "H")

  SSN <- replist$natage |>
    dplyr::filter(Yr %in% yrs, `Beg/Mid` == "B", Sex == sex) |>
    dplyr::select(Yr, Time, Seas, as.character(.GetSSAgeClasses(replist))) |>
    tidyr::pivot_longer(as.character(.GetSSAgeClasses(replist))) |>
    dplyr::mutate(Age = as.numeric(name)) |>
    dplyr::arrange(Age)

  SSN_Ages <- SSN$Age
  Seas <- unique(SSN$Seas)
  SSN$Age <- AgeClassesFull

  SSN <- SSN |>
    dplyr::arrange(Yr, Age) |>
    dplyr::filter(Age %in% AgeClasses)


  nSeas <- length(Seas)
  nTS <- length(yrs) * nSeas
  Yrs <- SSN$Yr |> unique()

  Initial <- array(NA, c(length(AgeClasses), nTS),
    dimnames = list(
      Age = AgeClasses,
      Year = HistYears[1:nTS]
    )
  )

  i <- 0
  for (yr in Yrs) {
    for (sea in 1:nSeas) {
      i <- i + 1
      n <- SSN |> dplyr::filter(Seas == sea, Yr < yr + 1 & Yr >= yr)
      temp <- array(n$value,
        dim = c(nrow(n), 1),
        dimnames = list(
          Age = n$Age,
          Year = HistYears[i]
        )
      )
      ArrayFill(Initial) <- temp
    }
  }

  Initial
}


#' Get Reference Points from Stock Synthesis Output
#'
#' Reads biological reference points from one or more Stock Synthesis (SS3)
#' model outputs and returns the requested quantities from the
#' `derived_quants` table.
#'
#' @param SSDir One of:
#'   - A character string giving the path to an SS3 output directory,
#'     passed to [ImportSSReport()].
#'   - A `RepList` object returned by [ImportSSReport()].
#'   - A plain list in `RepList` format, i.e. `RepList[[1]]`.
#' @param Labels Character vector of `derived_quants` labels to extract.
#'   Defaults to a standard set of F, catch, and biomass reference points:
#'
#'   - `"annF_F01"`, `"Dead_Catch_F01"` — F0.1 fishing mortality and dead catch.
#'   - `"SSB_SPR"`, `"annF_SPR"`, `"Dead_Catch_SPR"` — SSB, F, and dead catch
#'     at the SPR target.
#'   - `"SSB_MSY"`, `"SPR_MSY"`, `"annF_MSY"`, `"Dead_Catch_MSY"`,
#'     `"Ret_Catch_MSY"` — SSB, SPR, F, dead catch, and retained catch at MSY.
#'
#' @return If `SSDir` contains a single model, a data frame with columns:
#'
#'   - `Label` — the `derived_quants` label.
#'   - `Value` — the point estimate, rounded to 2 decimal places.
#'   - `StdDev` — the standard deviation, rounded to 2 decimal places.
#'
#'   If `SSDir` contains multiple models, a list of such data frames, one
#'   per model.
#'
#' @seealso [ImportSSReport()]
#' @export
GetSSRefPoints <- function(SSDir, Labels = c("annF_F01",
                                                 "Dead_Catch_F01",
                                                 "SSB_SPR",
                                                 "annF_SPR",
                                                 "Dead_Catch_SPR",
                                                 "SSB_MSY",
                                                 "SPR_MSY",
                                                 "annF_MSY",
                                                 "Dead_Catch_MSY",
                                                 "Ret_Catch_MSY")) {
  if (is.character(SSDir)) {
    RepList <- ImportSSReport(SSDir)
  } else if (inherits(SSDir, 'RepList')) {
    RepList <- SSDir
  } else if (is.list(SSDir)) {
    RepList <- list(SSDir)
  } else {
    cli::cli_abort(c('x'='`SSDir` must be a path to SS3 output or a `RepList` object returned by `ImportSSReport`'))
  }

  out <- purrr::map(RepList, \(replist) {
    replist$derived_quants |> dplyr::filter(Label %in% Labels) |>
      dplyr::select(Label, Value, StdDev) |>
      dplyr::mutate(Value = round(Value, 2), StdDev = round(StdDev, 2))
  })

  if (length(out) == 1)
    return(out[[1]])
  out
}
