#' Populate the `MeanAtAge` Slot of a Selectivity, Retention, or Similar Object
#'
#' Ensures `object@MeanAtAge` is a correctly structured and named
#' `Sim × Age × Year` array. Handles three input cases:
#'
#' - If `object@MeanAtAge` is already a named array, it is returned with
#'   dimension names assigned if missing.
#' - If `object@MeanAtAge` is a numeric vector of length `nAge`, it is
#'   promoted to a `1 × nAge × 1` array.
#' - If `object@Model` and `object@Pars` are populated, `MeanAtAge` is
#'   generated by calling the model function via [GenMeanAtAge()] or
#'   [GenMeanAtLength()], depending on whether the model expects `Ages` or
#'   `Length` arguments.
#'
#' Returns `object` unchanged if `object@Model` is `NULL` and `MeanAtAge` is
#' already populated.
#'
#' @param object An S4 object with slots `MeanAtAge`, `Model`, and `Pars`, and
#'   optionally `Timing` and `Classes`.
#' @param Ages An [ages-class] object supplying age class labels and count.
#'   Required when the model uses age-based inputs or when promoting a numeric
#'   vector.
#' @param Years Numeric vector of year labels. Used to assign the `Year`
#'   dimension when `MeanAtAge` lacks dimnames.
#' @param Length A [Length()] object. Required when `object@Model` expects a
#'   `Length` argument.
#'
#' @return `object` with `object@MeanAtAge` populated as a named
#'   `Sim × Age × Year` array.
#' @keywords internal
PopulateMeanAtAge <- function(object, Ages=NULL, Years=NULL, Length=NULL) {
  
  # Handle existing MeanAtAge 
  if (!is.null(object@MeanAtAge)) {
    
    if (!is.array(object@MeanAtAge)) {
      if (length(object@MeanAtAge) != length(Ages@Classes))
        cli::cli_abort(c(
          "x" = "If `MeanAtAge` is a numeric vector it must have length `nAge` ({.val {nAge(Ages)}}).",
          "i" = "Error occurred on object of class {.cls {class(object)}}."
        ))
      object@MeanAtAge <- array(
        object@MeanAtAge,
        dim      = c(1L, nAge(Ages), 1L),
        dimnames = list(Sim=1, Age=Ages@Classes, Year=Years[1])
      )
    }
    
    if (is.null(dimnames(object@MeanAtAge))) {
      dd <- dim(object@MeanAtAge)
      dimnames(object@MeanAtAge) <- list(
        Sim  = seq_len(dd[1]),
        Age  = Ages@Classes,
        Year = Years[seq_len(dd[3])]
      )
    }
  }
  
  # Generate MeanAtAge from Model and Pars 
  if (is.null(object@Model) || ParsEmpty(object@Pars))
    return(object)
  
  object@Model <- FindModel(object)
  args <- names(formals(object@Model))
  
  if ('Length' %in% args) {
    CheckRequiredObject(Length, 'length', 'Length')
    object@MeanAtAge <- GenMeanAtLength(
      Model  = object@Model,
      Pars   = object@Pars,
      Length = Length@MeanAtAge
    )
    object@Classes <- Length@Classes
    
  } else {
    if ('Ages' %in% args) {
      CheckRequiredObject(Ages, 'ages', 'Ages')
      if ('Timing' %in% slotNames(object) && !is.null(object@Timing))
        Ages@Classes <- Ages@Classes + object@Timing
    }
    object@MeanAtAge <- GenMeanAtAge(
      Model = object@Model,
      Pars  = object@Pars,
      Ages  = Ages@Classes
    )
  }
  
  object
}