#' Populate the `MeanAtAge` Slot of a Selectivity, Retention, or Similar Object
#'
#' Ensures `object@MeanAtAge` is a correctly structured and named
#' `Sim × Age × Year` array. Handles three input cases:
#'
#' - If `object@MeanAtAge` is already a named array, it is returned with
#'   dimension names assigned if missing.
#' - If `object@MeanAtAge` is a numeric vector of length `nAge`, it is
#'   promoted to a `1 × nAge × 1` array.
#' - If `object@Model` and `object@Pars` are populated, `MeanAtAge` is
#'   generated by calling the model function via [GenMeanAtAge()] or
#'   [GenMeanAtLength()], depending on whether the model expects `Ages` or
#'   `Length` arguments.
#'
#' Returns `object` unchanged if `object@Model` is `NULL` and `MeanAtAge` is
#' already populated.
#'
#' @param object An S4 object with slots `MeanAtAge`, `Model`, and `Pars`, and
#'   optionally `Timing` and `Classes`.
#' @param Ages An [ages-class] object supplying age class labels and count.
#'   Required when the model uses age-based inputs or when promoting a numeric
#'   vector.
#' @param Years Numeric vector of year labels. Used to assign the `Year`
#'   dimension when `MeanAtAge` lacks dimnames.
#' @param Length A [Length()] object. Required when `object@Model` expects a
#'   `Length` argument.
#'
#' @return `object` with `object@MeanAtAge` populated as a named
#'   `Sim × Age × Year` array.
#' @keywords internal
.PopulateMeanAtAge <- function(object, Ages=NULL, Years=NULL, Length=NULL) {

  # Handle existing MeanAtAge
  if (!is.null(object@MeanAtAge)) {

    if (!is.array(object@MeanAtAge)) {
      if (length(object@MeanAtAge) != length(Ages@Classes))
        cli::cli_abort(c(
          "x" = "If `MeanAtAge` is a numeric vector it must have length `nAge` ({.val {nAge(Ages)}}).",
          "i" = "Error occurred on object of class {.cls {class(object)}}."
        ))
      object@MeanAtAge <- array(
        object@MeanAtAge,
        dim      = c(1L, nAge(Ages), 1L),
        dimnames = list(Sim=1, Age=Ages@Classes, Year=Years[1])
      )
    }

    if (is.null(dimnames(object@MeanAtAge))) {
      dd <- dim(object@MeanAtAge)
      dimnames(object@MeanAtAge) <- list(
        Sim  = seq_len(dd[1]),
        Age  = Ages@Classes,
        Year = Years[seq_len(dd[3])]
      )
    }
  }

  # Generate MeanAtAge from Model and Pars
  if (is.null(object@Model) || .ParsEmpty(object@Pars))
    return(object)

  object@Model <- .FindModel(object)
  args <- names(formals(object@Model))

  if ('Length' %in% args) {
    .CheckRequiredObject(Length, 'length', 'Length')
    object@MeanAtAge <- GenMeanAtLength(
      Model  = object@Model,
      Pars   = object@Pars,
      Length = Length@MeanAtAge
    )
    object@Classes <- Length@Classes

  } else {
    if ('Ages' %in% args) {
      .CheckRequiredObject(Ages, 'ages', 'Ages')
      if ('Timing' %in% slotNames(object) && !is.null(object@Timing))
        Ages@Classes <- Ages@Classes + object@Timing
    }
    object@MeanAtAge <- GenMeanAtAge(
      Model = object@Model,
      Pars  = object@Pars,
      Ages  = Ages@Classes
    )
  }

  object
}


# Populates the `MeanAtLength` and `Classes` slot for a given object.
# `object@Classes` stores bin lower bounds; the model is evaluated at bin
# midpoints (via .ClassMidpoints()), but the output array is indexed by lower bounds.
.PopulateMeanAtLength <- function(object,
                                 Length=NULL,
                                 Years=NULL,
                                 Ages=NULL,
                                 seed=NULL,
                                 silent=FALSE) {

  if (is.null(object@Model))
    return(object)

  if (.ParsEmpty(object@Pars))
    return(object)

  if (is.null(object@Model))
    object@Model <- .FindModel(object)

  args <- names(formals(object@Model))

  if ('Ages' %in% args)
    return(object)

  if ('Length' %in% args)
    .CheckRequiredObject(Length, 'length', 'Length')

  if (is.null(object@Classes))
    object@Classes <- Length@Classes

  object@MeanAtLength <- GenMeanAtLength(Model  = object@Model,
                                         Pars   = object@Pars,
                                         Length = .ClassMidpoints(object@Classes))

  dd <- dim(object@MeanAtLength)
  if (length(dd) == 3) {
    dimnames(object@MeanAtLength) <- list(Sim   = 1:dd[1],
                                          Class = object@Classes,
                                          Year  = Years[1:dd[3]])
  } else {
    dimnames(object@MeanAtLength) <- list(Sim   = 1:dd[1],
                                          Class = object@Classes,
                                          Year  = Years[1:dd[3]],
                                          Area  = 1:dd[4])
  }

  object
}


#' Populate the `MeanAtWeight` Slot from a Model and Weight Object
#'
#' Generates `object@MeanAtWeight` by calling`GenMeanAtWeight` with
#' `object@Model`, `object@Pars`, and the size classes from `Weight`. Assigns
#' named `Sim × Class × Year` (or `Sim × Class × Year × Area`) dimnames to
#' the result.
#'
#' Returns `object` unchanged if `object@Model` is `NULL`, `object@Pars` is
#' empty, or if the model function expects `Ages` rather than weight-based
#' inputs (indicating this is an age-based rather than size-based object).
#'
#' @param object An S4 object with slots `MeanAtWeight`, `Model`, `Pars`, and
#'   `Classes`.
#' @param Weight A [Weight()] object supplying `Classes` (lower bounds of weight
#'   bins) used as size class labels. The model is evaluated at bin midpoints
#'   derived from these lower bounds.
#' @param Years Numeric vector of year labels used to assign the `Year`
#'   dimension of the output array.
#' @param Ages An [ages-class] object. Not used directly but checked to
#'   determine whether the model is age-based, in which case the function
#'   returns early.
#' @param seed Integer or `NULL`. Random seed for stochastic models. Reserved
#'   for future use.
#' @param silent Logical. If `TRUE`, suppresses messages. Reserved for future
#'   use. Default `FALSE`.
#'
#' @return `object` with `object@MeanAtWeight` and `object@Classes` populated,
#'   or `object` unchanged if the early-exit conditions are met.
#' @keywords internal
.PopulateMeanAtWeight <- function(object, Weight=NULL, Years=NULL,
                                 Ages=NULL, seed=NULL, silent=FALSE) {

  if (is.null(object@Model) || .ParsEmpty(object@Pars))
    return(object)

  object@Model <- .FindModel(object)
  args <- names(formals(object@Model))

  # Age-based model — MeanAtWeight not applicable
  if ('Ages' %in% args)
    return(object)

  if ('Weight' %in% args)
    .CheckRequiredObject(Weight, 'weight', 'Weight')

  object@MeanAtWeight <- GenMeanAtWeight(
    Model  = object@Model,
    Pars   = object@Pars,
    Weight = .ClassMidpoints(Weight@Classes)
  )
  object@Classes <- Weight@Classes

  dd     <- dim(object@MeanAtWeight)
  nDims  <- length(dd)
  Years_ <- Years[seq_len(dd[3])]

  dimnames(object@MeanAtWeight) <- if (nDims == 3) {
    list(
      Sim   = seq_len(dd[1]),
      Class = Weight@Classes,
      Year  = Years_
    )
  } else {
    list(
      Sim   = seq_len(dd[1]),
      Class = Weight@Classes,
      Year  = Years_,
      Area  = seq_len(dd[4])
    )
  }

  object
}
